// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPACommonAddin.cpp
// Provide implementation to interface
//    CATIShapeDesignWorkshopAddin
//    CATIPrtCfgAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Feb 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#include "TPACommonAddin.h"
#include "CATCreateWorkshop.h"
#include "CATIPrtCfgAddin.h"

CATImplementClass(TPACommonAddin,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 
 #include "CATCommandHeader.h"
 MacDeclareHeader(TPACommonHeader);
//-----------------------------------------------------------------------------
// TPACommonAddin : constructor
//-----------------------------------------------------------------------------
TPACommonAddin::TPACommonAddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// TPACommonAddin : destructor
//-----------------------------------------------------------------------------
TPACommonAddin::~TPACommonAddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIPrtCfgAddin.h"
TIE_CATIPrtCfgAddin(TPACommonAddin);
#include "TIE_CATIShapeDesignWorkshopAddin.h"
TIE_CATIShapeDesignWorkshopAddin(TPACommonAddin);


//Methods implementation

void TPACommonAddin::CreateCommands()
{
	new TPACommonHeader("TPAAutoDrawingCmdID", "TPAAutoDrawingModule", "TPAAutoDrawingCmd", NULL, CATFrmAvailable);
}
CATCmdContainer *TPACommonAddin::CreateToolbars()
{
	NewAccess(CATCmdContainer, pCommonContainer, TPALineMenubar);
	AddToolbarView(pCommonContainer, 1, Left);

	NewAccess(CATCmdStarter, pAutoDrawingCmd, TPACommonMenubar);
	SetAccessCommand(pAutoDrawingCmd, "TPAAutoDrawingCmdID"); 
	SetAccessChild(pCommonContainer, pAutoDrawingCmd); 
	return pCommonContainer;
}