// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPACommonAddin.h
// Provide implementation to interface
//    CATIShapeDesignWorkshopAddin
//    CATIPrtCfgAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//IMPLEMENTATION
//    TIE: CATIShapeDesignWorkshopAddin
//    TIE: CATIPrtCfgAddin

//End CAA2 Wizard Generation Report
//
//  Feb 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#ifndef TPACommonAddin_H
#define TPACommonAddin_H

#include "CATBaseUnknown.h"
#include "CATCmdContainer.h"


//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIShapeDesignWorkshopAddin
*  <li>@href CATIPrtCfgAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TPACommonAddin: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TPACommonAddin ();
     virtual ~TPACommonAddin ();
	 void CreateCommands();
	 CATCmdContainer * CreateToolbars();

  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TPACommonAddin (TPACommonAddin &);
  TPACommonAddin& operator=(TPACommonAddin&);

};

//-----------------------------------------------------------------------

#endif
