// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPADVSCommand.cpp
// The state chart based command: TPADVSCommand
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Apr 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#include "TPADVSCommand.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
#include "CATGeoFactory.h"
#include "CATVertex.h"
#include "CATFrmWindow.h"
#include "CATLine.h"
#include "CATI3DGeoVisu.h"
#include "CATRep.h"
#include "CAT3DLineRep.h"
#include "CATListOfCATString.h"
#include "TPAVolumetricDVSEngine.h"
#include "CATISpecObject.h"
#include "CATFrmEditor.h"
#include "ListPOfCATBody.h"









CATCreateClass( TPADVSCommand);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
TPADVSCommand::TPADVSCommand() :
  CATStateCommand ("TPADVSCommand", CATDlgEngOneShot, CATCommandModeExclusive) 
{
	_pTPACommonUtiliy = NULL;
	_pViewer = NULL;
	_pDVSDirView3DDlg = NULL;
	_pVehGeomMulLstContextMenu = NULL;
	_pHSO = NULL;
	_pPSO = NULL;
	_spGroundPlane = NULL_var;
	_spAccelKeyPt = NULL_var;
	_spSeatMidPt = NULL_var;
	_spLeftEyePoint = NULL_var;
	_spMidEyePoint = NULL_var;
	_spRightEyePoint = NULL_var;
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
TPADVSCommand::~TPADVSCommand()
{
	CATGeoFactory_var spGeoFactory = NULL_var;
	if (NULL != _pTPACommonUtiliy)
	{
		spGeoFactory = _pTPACommonUtiliy->GetPartGeoFactory();
	}
	if (spGeoFactory != NULL_var)
	{
		for (int i = 1; i <= _transientCGMBodies.Size(); ++i)
		{
			CATBody* pBody = _transientCGMBodies[i];
			if (pBody) spGeoFactory->Remove(pBody);
		}
	}
	_transientCGMBodies.RemoveAll();

	_pTPACommonUtiliy = NULL;
	if(NULL != _pDVSDirView3DDlg)
	{
		_pDVSDirView3DDlg->RequestDelayedDestruction();
		_pDVSDirView3DDlg = NULL;
	}
	if(NULL != _pViewer && NULL != _p3DBagRep)
	{
		_pViewer->RemoveRep(_p3DBagRep);
		_pViewer->Draw();
		_p3DBagRep->Destroy();
		_p3DBagRep = NULL;
	}
	if(NULL != _pVehGeomMulLstContextMenu)
	{
		_pVehGeomMulLstContextMenu->RequestDelayedDestruction();
		_pVehGeomMulLstContextMenu = NULL;
	}
	_pHSO = NULL;
	_pPSO = NULL;
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void TPADVSCommand::BuildGraph()
{
	_pDVSDirView3DDlg = new TPADVSDirectView3DDlg();
	_pDVSDirView3DDlg->Build();
	_pDVSDirView3DDlg->SetVisibility(CATDlgShow);
	CATFrmEditor *pEditor = CATFrmEditor::GetCurrentEditor();
	if(NULL == pEditor)
		return;
	_pHSO = pEditor->GetHSO();
	_pPSO = pEditor->GetPSO();
	if(NULL == _pHSO || NULL == _pPSO)
		return;
	CATFrmWindow *pWindow = CATFrmLayout::GetCurrentLayout()->GetCurrentWindow();
	if(NULL == pWindow)
		return;
	_p3DBagRep = new CAT3DBagRep();
	_pViewer = pWindow->GetViewer();
	_pTPACommonUtiliy = TPACommonUtilityClass::GetClassObject();
	if(NULL == _pTPACommonUtiliy)
		return;
	AddAnalyseNotificationCB(_pDVSDirView3DDlg, _pDVSDirView3DDlg->GetDiaAPPLYNotification(),(CATCommandMethod)&TPADVSCommand::ActionOnApply , (CATCommandClientData)CATINT32ToPtr(0));
	AddAnalyseNotificationCB(_pDVSDirView3DDlg, _pDVSDirView3DDlg->GetDiaOKNotification(),(CATCommandMethod)&TPADVSCommand::ActionOnOk , (CATCommandClientData)CATINT32ToPtr(0));
	AddAnalyseNotificationCB(_pDVSDirView3DDlg, _pDVSDirView3DDlg->GetDiaCLOSENotification(),(CATCommandMethod)&TPADVSCommand::ActionOnClose , (CATCommandClientData)CATINT32ToPtr(0));
	AddAnalyseNotificationCB(_pDVSDirView3DDlg, _pDVSDirView3DDlg->GetWindCloseNotification(),(CATCommandMethod)&TPADVSCommand::ActionOnClose , (CATCommandClientData)CATINT32ToPtr(0));
	AddAnalyseNotificationCB(_pDVSDirView3DDlg->GetVehicleGeometryMultiList(), _pDVSDirView3DDlg->GetVehicleGeometryMultiList()->GetListSelectNotification(),(CATCommandMethod)&TPADVSCommand::ActionOnVehicleGeomMultiList , (CATCommandClientData)CATINT32ToPtr(0));
	AddAnalyseNotificationCB(_pDVSDirView3DDlg->GetRadioButtGenFromAHP(), _pDVSDirView3DDlg->GetRadioButtGenFromAHP()->GetRadBttnNotification(),(CATCommandMethod)&TPADVSCommand::ActionOnRadioGenFromAHP , (CATCommandClientData)CATINT32ToPtr(0));
	AddAnalyseNotificationCB(_pDVSDirView3DDlg->GetRadioButtSelectDirectly(), _pDVSDirView3DDlg->GetRadioButtSelectDirectly()->GetRadBttnNotification(),(CATCommandMethod)&TPADVSCommand::ActionOnRadioSelectDirectly , (CATCommandClientData)CATINT32ToPtr(0));

	//Agents
	CATListOfCATString listOfAllowedSurfaces;
	_pPathEltAgentSeltSurfaces = new CATPathElementAgent("PathEltAgentSeltSurfacesID");
	_pPathEltAgentSeltSurfaces->SetBehavior( CATDlgEngWithPSOHSO  | CATDlgEngWithPrevaluation | CATDlgEngRepeat);
	listOfAllowedSurfaces.Append("CATIGSMAssemble");
	listOfAllowedSurfaces.Append("CATPoint");
	listOfAllowedSurfaces.Append("CATPlane");
	listOfAllowedSurfaces.Append("CATIGSMPoint");
	listOfAllowedSurfaces.Append("CATIGSMPlane");
	_pPathEltAgentSeltSurfaces->SetOrderedTypeList(listOfAllowedSurfaces);

	CATDialogState *pInitialState = GetInitialState("InitialStateID");
	pInitialState->AddDialogAgent(_pPathEltAgentSeltSurfaces);

	AddTransition ( pInitialState , pInitialState , IsOutputSetCondition(_pPathEltAgentSeltSurfaces) ,
         Action ( (ActionMethod) &TPADVSCommand::ActionOnSurfaceGeomSelect, NULL ) );
	_pVehGeomMulLstContextMenu = new CATDlgContextualMenu(_pDVSDirView3DDlg->GetVehicleGeometryMultiList(), "VehGeomMulLstContextMenuID"); 
    CATDlgPushItem* pRemoveItem = new CATDlgPushItem(_pVehGeomMulLstContextMenu,"Remove");
	AddAnalyseNotificationCB(pRemoveItem, pRemoveItem->GetMenuIActivateNotification(), (CATCommandMethod)&TPADVSCommand::ActionOnVechGeomMultiListRemove , (CATCommandClientData)CATINT32ToPtr(0));
}

//-------------------------------------------------------------------------
// ActionOnSurfaceGeomSelect ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnSurfaceGeomSelect()
{
	CATBoolean bSuccess = CATTrue;
	CATPathElement *pPathElement = _pPathEltAgentSeltSurfaces->GetValue();
	if(NULL == pPathElement)
		return bSuccess;
	CATISpecObject_var spSpecObj = pPathElement->FindElement(IID_CATISpecObject);
	if(!spSpecObj)
		return bSuccess;

	CATUnicodeString typeName = spSpecObj->GetType();
	CATUnicodeString usFeatName = TPACommonUtilityClass::GetClassObject()->GetNameOfFeature(spSpecObj);

	if (typeName.SearchSubString("Plane") >= 0)
	{
		_spGroundPlane = spSpecObj;
		if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetGroundPlaneEditor())
		{
			_pDVSDirView3DDlg->GetGroundPlaneEditor()->SetText(usFeatName);
		}
	}
	else if (typeName.SearchSubString("Point") >= 0)
	{
		CATBoolean isGenFromAHP = CATTrue;
		if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetRadioButtGenFromAHP())
		{
			isGenFromAHP = (_pDVSDirView3DDlg->GetRadioButtGenFromAHP()->GetState() == CATDlgCheck);
		}

		if (isGenFromAHP)
		{
			if (_spAccelKeyPt == NULL_var)
			{
				_spAccelKeyPt = spSpecObj;
				if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetAccelKeyPtEditor())
				{
					_pDVSDirView3DDlg->GetAccelKeyPtEditor()->SetText(usFeatName);
				}
			}
			else
			{
				_spSeatMidPt = spSpecObj;
				if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetSeatMidPtEditor())
				{
					_pDVSDirView3DDlg->GetSeatMidPtEditor()->SetText(usFeatName);
				}
			}
		}
		else
		{
			if (_spLeftEyePoint == NULL_var)
			{
				_spLeftEyePoint = spSpecObj;
				if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetLeftEyeEditor())
				{
					_pDVSDirView3DDlg->GetLeftEyeEditor()->SetText(usFeatName);
				}
			}
			else if (_spMidEyePoint == NULL_var)
			{
				_spMidEyePoint = spSpecObj;
				if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetMidEyeEditor())
				{
					_pDVSDirView3DDlg->GetMidEyeEditor()->SetText(usFeatName);
				}
			}
			else
			{
				_spRightEyePoint = spSpecObj;
				if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetRightEyeEditor())
				{
					_pDVSDirView3DDlg->GetRightEyeEditor()->SetText(usFeatName);
				}
			}
		}
	}
	else
	{
		_ListOfSelectedSurfaces.Append(spSpecObj);
		UpdateVehicleGeometryMultiList();
	}
	
	_pPathEltAgentSeltSurfaces->InitializeAcquisition();
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnSurfaceGeomSelect ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::UpdateVehicleGeometryMultiList()
{
	CATDlgMultiList *pMultiList = _pDVSDirView3DDlg->GetVehicleGeometryMultiList();
	pMultiList->ClearLine();
	for(int nSurfItr = 1; nSurfItr <= _ListOfSelectedSurfaces.Size(); ++nSurfItr)
	{
		CATUnicodeString usFeatName = TPACommonUtilityClass::GetClassObject()->GetNameOfFeature(_ListOfSelectedSurfaces[nSurfItr]);
		pMultiList->SetColumnItem(0, usFeatName);
		pMultiList->SetColumnItem(1, _ListOfSelectedSurfaces[nSurfItr]->GetType());
	}
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnVechGeomMultiListRemove ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnVechGeomMultiListRemove()
{
	_pHSO->Empty();
	_pPSO->Empty();
	CATDlgMultiList *pMultiList = _pDVSDirView3DDlg->GetVehicleGeometryMultiList();
	int nSelectedRow = pMultiList->GetSelectCount();
	if(nSelectedRow < 1)
		return FALSE;
	int *pArray = new int[nSelectedRow];
	pMultiList->GetSelect(pArray, nSelectedRow);
	for( int nRowItr = nSelectedRow -1; nRowItr >= 0; nRowItr--)
	{
		int nRowIndex = pArray[nRowItr];
		if(_ListOfSelectedSurfaces.Size() < (nRowIndex + 1))
			continue;
		_ListOfSelectedSurfaces.RemovePosition(nRowIndex+ 1);
	}
	UpdateVehicleGeometryMultiList();
	delete[] pArray;
	pArray = NULL;
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnVehicleGeomMultiList ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnVehicleGeomMultiList()
{
	_pHSO->Empty();
	_pPSO->Empty();
	CATDlgMultiList *pMultiList = _pDVSDirView3DDlg->GetVehicleGeometryMultiList();
	int nSelectedRow = pMultiList->GetSelectCount();
	if(nSelectedRow < 1)
		return FALSE;
	int *pArray = new int[nSelectedRow];
	pMultiList->GetSelect(pArray, nSelectedRow);
	for( int nRowItr = nSelectedRow -1; nRowItr >= 0; nRowItr--)
	{
		int nRowIndex = pArray[nRowItr];
		if(_ListOfSelectedSurfaces.Size() < (nRowIndex + 1))
			continue;
		CATPathElement *pPathElt = TPACommonUtilityClass::GetClassObject()->GetPathOfElement(_ListOfSelectedSurfaces[nRowIndex+ 1]);
		if(NULL == pPathElt)
			continue;
		_pHSO->AddElement(pPathElt);
		_pPSO->AddElement(pPathElt);
	}
	delete[] pArray;
	pArray = NULL;
	return TRUE;
}
//-------------------------------------------------------------------------
// ActionOnClose ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnClose()
{
	RequestDelayedDestruction();
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnApply ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnApply()
{
	int selectedIdx = 0;
	if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetStandardCombo())
	{
		selectedIdx = _pDVSDirView3DDlg->GetStandardCombo()->GetSelect();
	}

	if (selectedIdx == 0) // London DVS (TfL)
	{
		ActionOnComputeVolumetricDVS();
	}
	else
	{
		ActionOnCreateCone();
	}
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnOk ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnOk()
{
	RequestDelayedDestruction();
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnCreateCone()
{
	HRESULT hr = E_FAIL;
	if(NULL == _pViewer || NULL == _p3DBagRep)
		return FALSE;
	_pViewer->RemoveRep(_p3DBagRep);
	_p3DBagRep->Destroy();
	_pViewer->Draw();
	_p3DBagRep = new CAT3DBagRep();
	double nRotationAngle = _pDVSDirView3DDlg->GetRangeSpinner()->GetValue();
	double dAngleIncre = _pDVSDirView3DDlg->GetSliderAccuracry()->GetCurrentValue();
	CATGeoFactory_var spGeoFactory = _pTPACommonUtiliy->GetPartGeoFactory();
	if(!spGeoFactory)
		return FALSE;
	CATBaseUnknown_var spEyePoint = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "EyeSightPoint");
	CATBaseUnknown_var spLeftEyePoint = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "LeftSidePoint");
	CATBaseUnknown_var spRightEyePoint = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "RightSidePoint");
	if(!spEyePoint || !spLeftEyePoint || !spRightEyePoint)
		return FALSE;
	CATMathPoint ompEyePoint, ompLeftEyePoint, ompRightEyePoint;
	hr = _pTPACommonUtiliy->GetMathPointFromFeature(spEyePoint, ompEyePoint);
	if(FAILED(hr))
		return FALSE;
	hr = _pTPACommonUtiliy->GetMathPointFromFeature(spLeftEyePoint, ompLeftEyePoint);
	if(FAILED(hr))
		return FALSE;
	hr = _pTPACommonUtiliy->GetMathPointFromFeature(spRightEyePoint, ompRightEyePoint);
	if(FAILED(hr))
		return FALSE;
	CATMathPoint mpEyeSideBackPoint = (ompLeftEyePoint + ompRightEyePoint) / 2;
	CATMathVector  mvEyeSightDirection = ompEyePoint - mpEyeSideBackPoint;
	mvEyeSightDirection.Normalize();
	CATMathPoint mpEyeFrontPt = ompEyePoint + (10 * mvEyeSightDirection);
	CATMathVector mvFinalEyeSightVector = mpEyeFrontPt - ompEyePoint;
	mvFinalEyeSightVector.Normalize();
	CATMathPlane mpPlaneWithPoints(ompEyePoint, ompLeftEyePoint, ompRightEyePoint);
	CATMathVector mvNormalDir;
	mpPlaneWithPoints.GetNormal(mvNormalDir);
	mvNormalDir.Normalize();
	CATMathVector right = mvFinalEyeSightVector ^ mvNormalDir; 
	right.Normalize();
	CATLISTP(CATBody) listOfBodies;
	CATListPV listOfMathBoxes;
	for(int nSurItr = 1; nSurItr <= _ListOfSelectedSurfaces.Size(); ++nSurItr)
	{
		CATBody_var spBody = TPACommonUtilityClass::GetClassObject()->GetBodyFromFeature(_ListOfSelectedSurfaces[nSurItr]);
		if(!spBody)
			continue;
		listOfBodies.Append(spBody);
		CATMathBox ombMathBox = spBody->GetBoundingBox();
		listOfMathBoxes.Append(&ombMathBox);
	}
	for(double hAngle = -nRotationAngle; hAngle <= nRotationAngle; hAngle += dAngleIncre)
	{
		// Horizontal rotation
		CATMathVector horizDir =
			_pTPACommonUtiliy->RotateVector(
			mvFinalEyeSightVector,
			mvNormalDir,
			hAngle);

		for(double vAngle = -nRotationAngle; vAngle <= nRotationAngle; vAngle += dAngleIncre)
		{
			// Vertical rotation
			CATMathVector finalDir =
				_pTPACommonUtiliy->RotateVector(
				horizDir,
				right,
				vAngle);

			finalDir.Normalize();

			CATMathPoint endPt =
				ompEyePoint + (10000 * finalDir);

			// Calculate the bounding box of the line segment manually
			double xmin = ompEyePoint.GetX() < endPt.GetX() ? ompEyePoint.GetX() : endPt.GetX();
			double xmax = ompEyePoint.GetX() > endPt.GetX() ? ompEyePoint.GetX() : endPt.GetX();
			double ymin = ompEyePoint.GetY() < endPt.GetY() ? ompEyePoint.GetY() : endPt.GetY();
			double ymax = ompEyePoint.GetY() > endPt.GetY() ? ompEyePoint.GetY() : endPt.GetY();
			double zmin = ompEyePoint.GetZ() < endPt.GetZ() ? ompEyePoint.GetZ() : endPt.GetZ();
			double zmax = ompEyePoint.GetZ() > endPt.GetZ() ? ompEyePoint.GetZ() : endPt.GetZ();
			CATMathBox mathBox(xmin, xmax, ymin, ymax, zmin, zmax);

			CATBoolean bIntersectionFound = CATFalse;
			for(int nMathItr = 1; nMathItr <= listOfMathBoxes.Size(); nMathItr++)
			{
				CATMathBox *mathBoxBody = (CATMathBox*)listOfMathBoxes[nMathItr];
				if(NULL == mathBoxBody)
					continue;
				CATBoolean bIntersection = mathBoxBody->IsIntersecting(mathBox);
				if(bIntersection)
				{
					bIntersectionFound = CATTrue;
					break;
				}
			}
			if(bIntersectionFound == CATFalse)
				continue;

			// Construct a pure visualization line representation (does not pollute geometry container)
			double ptStart[3], ptEnd[3];
			ompEyePoint.GetCoord(ptStart);
			endPt.GetCoord(ptEnd);
			CAT3DLineRep* pRep = new CAT3DLineRep(ptStart, ptEnd);
			if(NULL != pRep)
			{
				pRep->SetInheritanceMode(COLOR_INHERITANCE);
				pRep->GetGraphicAttributeSet().SetColor(GREEN);

				_p3DBagRep->AddChild(*pRep);
			}
		}
	}
	_pViewer->AddRep(_p3DBagRep);
	_pViewer->Draw();
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnComputeVolumetricDVS ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnComputeVolumetricDVS()
{
	HRESULT hr = E_FAIL;
	if (NULL == _pViewer || NULL == _p3DBagRep || NULL == _pTPACommonUtiliy)
		return FALSE;

	_pViewer->RemoveRep(_p3DBagRep);
	_p3DBagRep->Destroy();
	_pViewer->Draw();
	_p3DBagRep = new CAT3DBagRep();

	// Retrieve the active CATIA geometry factory
	CATGeoFactory_var spGeoFactory = _pTPACommonUtiliy->GetPartGeoFactory();
	if (!spGeoFactory)
		return FALSE;

	// 1. Clean up transient bodies from the previous run to prevent leaks
	if (spGeoFactory != NULL_var)
	{
		for (int i = 1; i <= _transientCGMBodies.Size(); ++i)
		{
			CATBody* pBody = _transientCGMBodies[i];
			if (pBody) spGeoFactory->Remove(pBody);
		}
	}
	_transientCGMBodies.RemoveAll();

	// 2. Retrieve Eye Points & Ground Plane
	CATMathPoint mpLeftEye, mpRightEye, mpEyeCenter;
	CATMathPoint gpPoint(0.0, 0.0, 0.0);
	double groundZ = 0.0;
	if (_spGroundPlane != NULL_var)
	{
		_pTPACommonUtiliy->GetMathPointFromFeature(_spGroundPlane, gpPoint);
		groundZ = gpPoint.GetZ();
	}

	// 3. Initialize the modular Volumetric Compliance Engine
	TPAVolumetricDVSEngine engine(spGeoFactory);

	CATBoolean isGenFromAHP = CATTrue;
	if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetRadioButtGenFromAHP())
	{
		isGenFromAHP = (_pDVSDirView3DDlg->GetRadioButtGenFromAHP()->GetState() == CATDlgCheck);
	}

	if (isGenFromAHP)
	{
		CATMathPoint mpAHP, mpSeatMid;
		CATBaseUnknown_var spAHP = _spAccelKeyPt;
		CATBaseUnknown_var spSeatMid = _spSeatMidPt;

		if (!spAHP)
		{
			spAHP = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "LeftSidePoint");
		}
		if (!spSeatMid)
		{
			spSeatMid = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "RightSidePoint");
		}

		if (!spAHP || !spSeatMid)
			return FALSE;

		hr = _pTPACommonUtiliy->GetMathPointFromFeature(spAHP, mpAHP);
		if (FAILED(hr)) return FALSE;

		hr = _pTPACommonUtiliy->GetMathPointFromFeature(spSeatMid, mpSeatMid);
		if (FAILED(hr)) return FALSE;

		double dLengthOffset = 678.0;
		if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetLengthOffsetSpinner())
		{
			dLengthOffset = _pDVSDirView3DDlg->GetLengthOffsetSpinner()->GetValue();
		}

		// Dynamic forward vector determination
		CATMathVector mvForwardDir(-1.0, 0.0, 0.0); // Default forward (-X)
		CATMathVector mvUpDir(0.0, 0.0, 1.0); // Default up (+Z)
		CATBaseUnknown_var spDefaultEye = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "EyeSightPoint");
		CATBaseUnknown_var spDefaultLeft = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "LeftSidePoint");
		CATBaseUnknown_var spDefaultRight = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "RightSidePoint");
		if (spDefaultEye != NULL_var && spDefaultLeft != NULL_var && spDefaultRight != NULL_var)
		{
			CATMathPoint ptEye, ptLeft, ptRight;
			_pTPACommonUtiliy->GetMathPointFromFeature(spDefaultEye, ptEye);
			_pTPACommonUtiliy->GetMathPointFromFeature(spDefaultLeft, ptLeft);
			_pTPACommonUtiliy->GetMathPointFromFeature(spDefaultRight, ptRight);
			CATMathPoint ptBack = (ptLeft + ptRight) / 2.0;
			mvForwardDir = ptEye - ptBack;
			mvForwardDir.Normalize();
		}

		hr = engine.GenerateEyePointsFromAHP(mpAHP, mpSeatMid, dLengthOffset, mvForwardDir, mvUpDir, mpLeftEye, mpEyeCenter, mpRightEye);
		if (FAILED(hr)) return FALSE;
	}
	else
	{
		CATBaseUnknown_var spLeft = _spLeftEyePoint;
		CATBaseUnknown_var spMid = _spMidEyePoint;
		CATBaseUnknown_var spRight = _spRightEyePoint;

		if (!spLeft || !spMid || !spRight)
		{
			spLeft = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "LeftSidePoint");
			spMid = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "EyeSightPoint");
			spRight = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "RightSidePoint");
		}

		if (!spLeft || !spMid || !spRight)
			return FALSE;

		hr = _pTPACommonUtiliy->GetMathPointFromFeature(spLeft, mpLeftEye);
		if (FAILED(hr)) return FALSE;

		hr = _pTPACommonUtiliy->GetMathPointFromFeature(spMid, mpEyeCenter);
		if (FAILED(hr)) return FALSE;

		hr = _pTPACommonUtiliy->GetMathPointFromFeature(spRight, mpRightEye);
		if (FAILED(hr)) return FALSE;
	}

	// 4. Step 1: SAV Construction based on Standard
	int iStandard = 0;
	if (NULL != _pDVSDirView3DDlg && NULL != _pDVSDirView3DDlg->GetStandardCombo())
	{
		iStandard = _pDVSDirView3DDlg->GetStandardCombo()->GetSelect();
	}

	CATBody* pSAVBody = NULL;
	hr = engine.CreateStandardAssessmentVolume(mpEyeCenter, groundZ, iStandard, pSAVBody);
	if (FAILED(hr) || NULL == pSAVBody)
		return FALSE;

	// 5. Step 2: Cone Generation (Sight Cones passing through glazing)
	CATBody* pSightCone = NULL;
	hr = engine.GenerateSightCones(mpEyeCenter, _ListOfSelectedSurfaces, pSightCone);
	if (FAILED(hr) || NULL == pSightCone)
	{
		if (pSAVBody) spGeoFactory->Remove(pSAVBody);
		return FALSE;
	}

	// 6. Step 3: Shadow Casting (Generating shadow solids from driver's eye position)
	CATLISTP(CATBody) shadowBodies;
	hr = engine.GenerateObstacleShadows(mpEyeCenter, _ListOfObstacleBodies, 10000.0, shadowBodies);

	// Retrieve obstacle bodies list
	CATLISTP(CATBody) obstacleBodies;
	for (int nObs = 1; nObs <= _ListOfObstacleBodies.Size(); ++nObs)
	{
		CATBody_var spObsBody = _pTPACommonUtiliy->GetBodyFromFeature(_ListOfObstacleBodies[nObs]);
		if (spObsBody != NULL_var)
		{
			obstacleBodies.Append((CATBody*)spObsBody);
		}
	}

	// 7. Step 4: Boolean Cut (Subtract obstacles/shadows, intersect with SAV)
	CATBody* pVisibleVolume = NULL;
	hr = engine.ComputeVisibilityVolume(pSightCone, obstacleBodies, shadowBodies, pSAVBody, pVisibleVolume);

	// 8. Step 5: Measurement (Mass properties calculation in cubic meters)
	double dVolumeM3 = 0.0;
	if (SUCCEEDED(hr) && NULL != pVisibleVolume)
	{
		hr = engine.MeasureVisibleVolume(pVisibleVolume, dVolumeM3);
	}

	// 9. Update viewport visualization with intermediate and final solids
	
	// A. Visualize the Standard Assessment Volume (SAV) in BLUE
	if (NULL != pSAVBody)
	{
		CATI3DGeoVisu_var spVisuSAV = pSAVBody;
		if (spVisuSAV != NULL_var)
		{
			CATRep* pRepSAV = spVisuSAV->BuildRep();
			if (NULL != pRepSAV)
			{
				pRepSAV->SetInheritanceMode(COLOR_INHERITANCE);
				pRepSAV->GetGraphicAttributeSet().SetColor(BLUE);
				_p3DBagRep->AddChild(*pRepSAV);
			}
		}
	}

	// B. Visualize the Raw Sight Cone in CYAN
	if (NULL != pSightCone)
	{
		CATI3DGeoVisu_var spVisuCone = pSightCone;
		if (spVisuCone != NULL_var)
		{
			CATRep* pRepCone = spVisuCone->BuildRep();
			if (NULL != pRepCone)
			{
				pRepCone->SetInheritanceMode(COLOR_INHERITANCE);
				pRepCone->GetGraphicAttributeSet().SetColor(CYAN);
				_p3DBagRep->AddChild(*pRepCone);
			}
		}
	}

	// C. Visualize all Obscuration / Shadow Volumes in RED
	for (int nShadItr = 1; nShadItr <= shadowBodies.Size(); ++nShadItr)
	{
		CATBody* pShad = shadowBodies[nShadItr];
		if (NULL != pShad)
		{
			CATI3DGeoVisu_var spVisuShad = pShad;
			if (spVisuShad != NULL_var)
			{
				CATRep* pRepShad = spVisuShad->BuildRep();
				if (NULL != pRepShad)
				{
					pRepShad->SetInheritanceMode(COLOR_INHERITANCE);
					pRepShad->GetGraphicAttributeSet().SetColor(RED);
					_p3DBagRep->AddChild(*pRepShad);
				}
			}
		}
	}

	// D. Visualize the Final Visible Volume in GREEN
	if (NULL != pVisibleVolume)
	{
		CATI3DGeoVisu_var sp3DGeoVisu = pVisibleVolume;
		if (sp3DGeoVisu != NULL_var)
		{
			CATRep* pRep = sp3DGeoVisu->BuildRep();
			if (NULL != pRep)
			{
				pRep->SetInheritanceMode(COLOR_INHERITANCE);
				pRep->GetGraphicAttributeSet().SetColor(GREEN);
				_p3DBagRep->AddChild(*pRep);
			}
		}
	}

	_pViewer->AddRep(_p3DBagRep);
	_pViewer->Draw();

	// 10. Register bodies in transient list for visual retention and later clean-up
	if (pSightCone) _transientCGMBodies.Append(pSightCone);
	if (pSAVBody) _transientCGMBodies.Append(pSAVBody);
	if (pVisibleVolume) _transientCGMBodies.Append(pVisibleVolume);
	for (int nShad = 1; nShad <= shadowBodies.Size(); ++nShad)
	{
		CATBody* pShad = shadowBodies[nShad];
		if (pShad) _transientCGMBodies.Append(pShad);
	}

	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnRadioGenFromAHP ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnRadioGenFromAHP()
{
	if (NULL == _pDVSDirView3DDlg) return TRUE;
	_pDVSDirView3DDlg->GetRadioButtGenFromAHP()->SetState(CATDlgCheck, TRUE);
	_pDVSDirView3DDlg->GetRadioButtSelectDirectly()->SetState(CATDlgCheck, FALSE);

	_pDVSDirView3DDlg->GetAccelKeyPtEditor()->SetSensitivity(CATDlgEnable);
	_pDVSDirView3DDlg->GetSeatMidPtEditor()->SetSensitivity(CATDlgEnable);
	_pDVSDirView3DDlg->GetLengthOffsetSpinner()->SetSensitivity(CATDlgEnable);

	_pDVSDirView3DDlg->GetLeftEyeEditor()->SetSensitivity(CATDlgDisable);
	_pDVSDirView3DDlg->GetMidEyeEditor()->SetSensitivity(CATDlgDisable);
	_pDVSDirView3DDlg->GetRightEyeEditor()->SetSensitivity(CATDlgDisable);

	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnRadioSelectDirectly ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnRadioSelectDirectly()
{
	if (NULL == _pDVSDirView3DDlg) return TRUE;
	_pDVSDirView3DDlg->GetRadioButtGenFromAHP()->SetState(CATDlgCheck, FALSE);
	_pDVSDirView3DDlg->GetRadioButtSelectDirectly()->SetState(CATDlgCheck, TRUE);

	_pDVSDirView3DDlg->GetAccelKeyPtEditor()->SetSensitivity(CATDlgDisable);
	_pDVSDirView3DDlg->GetSeatMidPtEditor()->SetSensitivity(CATDlgDisable);
	_pDVSDirView3DDlg->GetLengthOffsetSpinner()->SetSensitivity(CATDlgDisable);

	_pDVSDirView3DDlg->GetLeftEyeEditor()->SetSensitivity(CATDlgEnable);
	_pDVSDirView3DDlg->GetMidEyeEditor()->SetSensitivity(CATDlgEnable);
	_pDVSDirView3DDlg->GetRightEyeEditor()->SetSensitivity(CATDlgEnable);

	return TRUE;
}