// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPADVSAddin.cpp
// Provide implementation to interface
//    CATIAfrGeneralWksAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Apr 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#include "TPADVSAddin.h"
#include "CATCommandHeader.h"
MacDeclareHeader(TPAVolvoHeader);
#include "CATCreateWorkshop.h"

CATImplementClass(TPADVSAddin,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 

//-----------------------------------------------------------------------------
// TPADVSAddin : constructor
//-----------------------------------------------------------------------------
TPADVSAddin::TPADVSAddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// TPADVSAddin : destructor
//-----------------------------------------------------------------------------
TPADVSAddin::~TPADVSAddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIAfrGeneralWksAddin.h"
TIE_CATIAfrGeneralWksAddin(TPADVSAddin);


//Methods implementation

void TPADVSAddin::CreateCommands()
{
	new TPAVolvoHeader("TPADVSCmdID", "TPADVSAuto", "TPADVSCommand", NULL, CATFrmAvailable);
}
CATCmdContainer *TPADVSAddin::CreateToolbars()
{
	NewAccess(CATCmdContainer, pDVSContainer, TPAVolvo);
	AddToolbarView(pDVSContainer, 1, Left);

	NewAccess(CATCmdStarter, pDVSCommand, TPADVSMenubar);
	SetAccessCommand(pDVSCommand, "TPADVSCmdID"); 
	SetAccessChild(pDVSContainer, pDVSCommand); 
	return pDVSContainer;
}