// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPADVSCommand.cpp
// The state chart based command: TPADVSCommand
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Apr 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#include "TPADVSCommand.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
#include "CATGeoFactory.h"
#include "CATVertex.h"
#include "CATFrmWindow.h"
#include "CATLine.h"
#include "CATI3DGeoVisu.h"
#include "CATRep.h"
#include "CATListOfCATString.h"
#include "CATISpecObject.h"
#include "CATFrmEditor.h"
#include "ListPOfCATBody.h"









CATCreateClass( TPADVSCommand);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
TPADVSCommand::TPADVSCommand() :
  CATStateCommand ("TPADVSCommand", CATDlgEngOneShot, CATCommandModeExclusive) 
{
	_pTPACommonUtiliy = NULL;
	_pViewer = NULL;
	_pDVSDirView3DDlg = NULL;
	_pVehGeomMulLstContextMenu = NULL;
	_pHSO = NULL;
	_pPSO = NULL;
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
TPADVSCommand::~TPADVSCommand()
{
	_pTPACommonUtiliy = NULL;
	if(NULL != _pDVSDirView3DDlg)
	{
		_pDVSDirView3DDlg->RequestDelayedDestruction();
		_pDVSDirView3DDlg = NULL;
	}
	if(NULL != _pViewer && NULL != _p3DBagRep)
	{
		_pViewer->RemoveRep(_p3DBagRep);
		_pViewer->Draw();
		_p3DBagRep->Destroy();
		_p3DBagRep = NULL;
	}
	if(NULL != _pVehGeomMulLstContextMenu)
	{
		_pVehGeomMulLstContextMenu->RequestDelayedDestruction();
		_pVehGeomMulLstContextMenu = NULL;
	}
	_pHSO = NULL;
	_pPSO = NULL;
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void TPADVSCommand::BuildGraph()
{
	_pDVSDirView3DDlg = new TPADVSDirectView3DDlg();
	_pDVSDirView3DDlg->Build();
	_pDVSDirView3DDlg->SetVisibility(CATDlgShow);
	CATFrmEditor *pEditor = CATFrmEditor::GetCurrentEditor();
	if(NULL == pEditor)
		return;
	_pHSO = pEditor->GetHSO();
	_pPSO = pEditor->GetPSO();
	if(NULL == _pHSO || NULL == _pPSO)
		return;
	CATFrmWindow *pWindow = CATFrmLayout::GetCurrentLayout()->GetCurrentWindow();
	if(NULL == pWindow)
		return;
	_p3DBagRep = new CAT3DBagRep();
	_pViewer = pWindow->GetViewer();
	_pTPACommonUtiliy = TPACommonUtilityClass::GetClassObject();
	if(NULL == _pTPACommonUtiliy)
		return;
	AddAnalyseNotificationCB(_pDVSDirView3DDlg, _pDVSDirView3DDlg->GetDiaAPPLYNotification(),(CATCommandMethod)&TPADVSCommand::ActionOnApply , (CATCommandClientData)CATINT32ToPtr(0));
	AddAnalyseNotificationCB(_pDVSDirView3DDlg, _pDVSDirView3DDlg->GetDiaOKNotification(),(CATCommandMethod)&TPADVSCommand::ActionOnOk , (CATCommandClientData)CATINT32ToPtr(0));
	AddAnalyseNotificationCB(_pDVSDirView3DDlg, _pDVSDirView3DDlg->GetDiaCLOSENotification(),(CATCommandMethod)&TPADVSCommand::ActionOnClose , (CATCommandClientData)CATINT32ToPtr(0));
	AddAnalyseNotificationCB(_pDVSDirView3DDlg, _pDVSDirView3DDlg->GetWindCloseNotification(),(CATCommandMethod)&TPADVSCommand::ActionOnClose , (CATCommandClientData)CATINT32ToPtr(0));
	AddAnalyseNotificationCB(_pDVSDirView3DDlg->GetVehicleGeometryMultiList(), _pDVSDirView3DDlg->GetVehicleGeometryMultiList()->GetListSelectNotification(),(CATCommandMethod)&TPADVSCommand::ActionOnVehicleGeomMultiList , (CATCommandClientData)CATINT32ToPtr(0));

	//Agents
	CATListOfCATString listOfAllowedSurfaces;
	_pPathEltAgentSeltSurfaces = new CATPathElementAgent("PathEltAgentSeltSurfacesID");
	_pPathEltAgentSeltSurfaces->SetBehavior( CATDlgEngWithPSOHSO  | CATDlgEngWithPrevaluation | CATDlgEngRepeat);
	listOfAllowedSurfaces.Append("CATIGSMAssemble");
	_pPathEltAgentSeltSurfaces->SetOrderedTypeList(listOfAllowedSurfaces);

	CATDialogState *pInitialState = GetInitialState("InitialStateID");
	pInitialState->AddDialogAgent(_pPathEltAgentSeltSurfaces);

	AddTransition ( pInitialState , pInitialState , IsOutputSetCondition(_pPathEltAgentSeltSurfaces) ,
         Action ( (ActionMethod) &TPADVSCommand::ActionOnSurfaceGeomSelect, NULL ) );
	_pVehGeomMulLstContextMenu = new CATDlgContextualMenu(_pDVSDirView3DDlg->GetVehicleGeometryMultiList(), "VehGeomMulLstContextMenuID"); 
    CATDlgPushItem* pRemoveItem = new CATDlgPushItem(_pVehGeomMulLstContextMenu,"Remove");
	AddAnalyseNotificationCB(pRemoveItem, pRemoveItem->GetMenuIActivateNotification(), (CATCommandMethod)&TPADVSCommand::ActionOnVechGeomMultiListRemove , (CATCommandClientData)CATINT32ToPtr(0));
}

//-------------------------------------------------------------------------
// ActionOnSurfaceGeomSelect ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnSurfaceGeomSelect()
{
	CATBoolean bSuccess = CATTrue;
	CATPathElement *pPathElement = _pPathEltAgentSeltSurfaces->GetValue();
	if(NULL == pPathElement)
		return bSuccess;
	CATISpecObject_var spSpecObj = pPathElement->FindElement(IID_CATISpecObject);
	if(!spSpecObj)
		return bSuccess;
	_ListOfSelectedSurfaces.Append(spSpecObj);
	UpdateVehicleGeometryMultiList();
	CATUnicodeString usFeatName = TPACommonUtilityClass::GetClassObject()->GetNameOfFeature(spSpecObj);
	
	_pPathEltAgentSeltSurfaces->InitializeAcquisition();
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnSurfaceGeomSelect ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::UpdateVehicleGeometryMultiList()
{
	CATDlgMultiList *pMultiList = _pDVSDirView3DDlg->GetVehicleGeometryMultiList();
	pMultiList->ClearLine();
	for(int nSurfItr = 1; nSurfItr <= _ListOfSelectedSurfaces.Size(); ++nSurfItr)
	{
		CATUnicodeString usFeatName = TPACommonUtilityClass::GetClassObject()->GetNameOfFeature(_ListOfSelectedSurfaces[nSurfItr]);
		pMultiList->SetColumnItem(0, usFeatName);
		pMultiList->SetColumnItem(1, _ListOfSelectedSurfaces[nSurfItr]->GetType());
	}
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnVechGeomMultiListRemove ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnVechGeomMultiListRemove()
{
	_pHSO->Empty();
	_pPSO->Empty();
	CATDlgMultiList *pMultiList = _pDVSDirView3DDlg->GetVehicleGeometryMultiList();
	int nSelectedRow = pMultiList->GetSelectCount();
	if(nSelectedRow < 1)
		return FALSE;
	int *pArray = new int[nSelectedRow];
	pMultiList->GetSelect(pArray, nSelectedRow);
	for( int nRowItr = nSelectedRow -1; nRowItr >= 0; nRowItr--)
	{
		int nRowIndex = pArray[nRowItr];
		if(_ListOfSelectedSurfaces.Size() < (nRowIndex + 1))
			continue;
		_ListOfSelectedSurfaces.RemovePosition(nRowIndex+ 1);
	}
	UpdateVehicleGeometryMultiList();
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnVehicleGeomMultiList ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnVehicleGeomMultiList()
{
	_pHSO->Empty();
	_pPSO->Empty();
	CATDlgMultiList *pMultiList = _pDVSDirView3DDlg->GetVehicleGeometryMultiList();
	int nSelectedRow = pMultiList->GetSelectCount();
	if(nSelectedRow < 1)
		return FALSE;
	int *pArray = new int[nSelectedRow];
	pMultiList->GetSelect(pArray, nSelectedRow);
	for( int nRowItr = nSelectedRow -1; nRowItr >= 0; nRowItr--)
	{
		int nRowIndex = pArray[nRowItr];
		if(_ListOfSelectedSurfaces.Size() < (nRowIndex + 1))
			continue;
		CATPathElement *pPathElt = TPACommonUtilityClass::GetClassObject()->GetPathOfElement(_ListOfSelectedSurfaces[nRowIndex+ 1]);
		if(NULL == pPathElt)
			continue;
		_pHSO->AddElement(pPathElt);
		_pPSO->AddElement(pPathElt);
	}
	return TRUE;
}
//-------------------------------------------------------------------------
// ActionOnClose ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnClose()
{
	RequestDelayedDestruction();
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnApply ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnApply()
{
	ActionOnCreateCone();
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOnOk ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnOk()
{
	RequestDelayedDestruction();
	return TRUE;
}

//-------------------------------------------------------------------------
// ActionOne ()
//-------------------------------------------------------------------------
CATBoolean TPADVSCommand::ActionOnCreateCone()
{
	HRESULT hr = E_FAIL;
	if(NULL == _pViewer || NULL == _p3DBagRep)
		return FALSE;
	_pViewer->RemoveRep(_p3DBagRep);
	_p3DBagRep->Destroy();
	_pViewer->Draw();
	_p3DBagRep = new CAT3DBagRep();
	double nRotationAngle = _pDVSDirView3DDlg->GetRangeSpinner()->GetValue();
	double dAngleIncre = _pDVSDirView3DDlg->GetSliderAccuracry()->GetCurrentValue();
	CATGeoFactory_var spGeoFactory = _pTPACommonUtiliy->GetPartGeoFactory();
	if(!spGeoFactory)
		return FALSE;
	CATBaseUnknown_var spEyePoint = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "EyeSightPoint");
	CATBaseUnknown_var spLeftEyePoint = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "LeftSidePoint");
	CATBaseUnknown_var spRightEyePoint = _pTPACommonUtiliy->FindElementByName(_pTPACommonUtiliy->GetRootElement(), "RightSidePoint");
	if(!spEyePoint || !spLeftEyePoint || !spRightEyePoint)
		return FALSE;
	CATMathPoint ompEyePoint, ompLeftEyePoint, ompRightEyePoint;
	hr = _pTPACommonUtiliy->GetMathPointFromFeature(spEyePoint, ompEyePoint);
	if(FAILED(hr))
		return FALSE;
	hr = _pTPACommonUtiliy->GetMathPointFromFeature(spLeftEyePoint, ompLeftEyePoint);
	if(FAILED(hr))
		return FALSE;
	hr = _pTPACommonUtiliy->GetMathPointFromFeature(spRightEyePoint, ompRightEyePoint);
	if(FAILED(hr))
		return FALSE;
	CATMathPoint mpEyeSideBackPoint = (ompLeftEyePoint + ompRightEyePoint) / 2;
	CATMathVector  mvEyeSightDirection = ompEyePoint - mpEyeSideBackPoint;
	mvEyeSightDirection.Normalize();
	CATMathPoint mpEyeFrontPt = ompEyePoint + (10 * mvEyeSightDirection);
	CATMathVector mvFinalEyeSightVector = mpEyeFrontPt - ompEyePoint;
	mvFinalEyeSightVector.Normalize();
	CATMathPlane mpPlaneWithPoints(ompEyePoint, ompLeftEyePoint, ompRightEyePoint);
	CATMathVector mvNormalDir;
	mpPlaneWithPoints.GetNormal(mvNormalDir);
	mvNormalDir.Normalize();
	CATMathVector right = mvFinalEyeSightVector ^ mvNormalDir; 
	right.Normalize();
	CATLISTP(CATBody) listOfBodies;
	CATListPV listOfMathBoxes;
	for(int nSurItr = 1; nSurItr <= _ListOfSelectedSurfaces.Size(); ++nSurItr)
	{
		CATBody_var spBody = TPACommonUtilityClass::GetClassObject()->GetBodyFromFeature(_ListOfSelectedSurfaces[nSurItr]);
		if(!spBody)
			continue;
		listOfBodies.Append(spBody);
		CATMathBox ombMathBox = spBody->GetBoundingBox();
		listOfMathBoxes.Append(&ombMathBox);
	}
	for(double hAngle = -nRotationAngle; hAngle <= nRotationAngle; hAngle += dAngleIncre)
	{
		// Horizontal rotation
		CATMathVector horizDir =
			_pTPACommonUtiliy->RotateVector(
			mvFinalEyeSightVector,
			mvNormalDir,
			hAngle);

		for(double vAngle = -nRotationAngle; vAngle <= nRotationAngle; vAngle += dAngleIncre)
		{
			// Vertical rotation
			CATMathVector finalDir =
				_pTPACommonUtiliy->RotateVector(
				horizDir,
				right,
				vAngle);

			finalDir.Normalize();

			CATMathPoint endPt =
				ompEyePoint + (10000 * finalDir);

			CATLine* pLine =
				spGeoFactory->CreateLine(
				ompEyePoint,
				endPt);

			if(NULL != pLine)
			{
				CATMathBox mathBox = pLine->GetBoundingBox();
				CATBoolean bIntersectionFound = CATFalse;
				for(int nMathItr = 1; nMathItr <= listOfMathBoxes.Size(); nMathItr++)
				{
					CATMathBox *mathBoxBody = (CATMathBox*)listOfMathBoxes[nMathItr];
					if(NULL == mathBoxBody)
						continue;
					CATBoolean bIntersection = mathBoxBody->IsIntersecting(mathBox);
					if(bIntersection)
					{
						bIntersectionFound = CATTrue;
						break;
					}
				}
				if(bIntersectionFound == CATFalse)
					continue;
				CATI3DGeoVisu_var sp3DGeoVisu = pLine;

				if(!sp3DGeoVisu)
					continue;

				CATRep* pRep = sp3DGeoVisu->BuildRep();

				if(NULL == pRep)
					continue;

				pRep->SetInheritanceMode(COLOR_INHERITANCE);
				pRep->GetGraphicAttributeSet().SetColor(GREEN);

				_p3DBagRep->AddChild(*pRep);
			}
		}
	}
	_pViewer->AddRep(_p3DBagRep);
	_pViewer->Draw();
	return TRUE;
}