// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPADVSCommand.h
// The state chart based command: TPADVSCommand
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Apr 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#ifndef TPADVSCommand_H
#define TPADVSCommand_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "TPACommonUtilityClass.h"
#include "CATBaseUnknown.h"
#include "CATViewer.h"
#include "CAT3DBagRep.h"
#include "TPADVSDirectView3DDlg.h"
#include "CATPathElementAgent.h"
#include "CATHSO.h"
#include "CATPSO.h"
#include "ListPOfCATBody.h"





#define LeftDirection  "LeftDirection"
#define RightDirection "RightDirection"
#define StraightDireciton "StraightDirection"

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class TPADVSCommand: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TPADVSCommand, CATStateCommand )

  public:

  TPADVSCommand();
  virtual ~TPADVSCommand();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOnCreateCone();
  virtual CATBoolean  ActionOnApply();
  virtual CATBoolean  ActionOnOk(); 
  virtual CATBoolean  ActionOnClose();
  virtual CATBoolean ActionOnSurfaceGeomSelect();
  virtual CATBoolean UpdateVehicleGeometryMultiList();
  virtual CATBoolean ActionOnVechGeomMultiListRemove();
  virtual CATBoolean ActionOnVehicleGeomMultiList();

  public:
	  virtual CATBoolean ActionOnComputeVolumetricDVS();

  private:
	  TPACommonUtilityClass *_pTPACommonUtiliy;
	  CATViewer				*_pViewer;
	  CAT3DBagRep			*_p3DBagRep;
	  TPADVSDirectView3DDlg	*_pDVSDirView3DDlg;
	  CATPathElementAgent   *_pPathEltAgentSeltSurfaces;
	  CATLISTV(CATISpecObject_var) _ListOfSelectedSurfaces;
	  CATDlgContextualMenu  *_pVehGeomMulLstContextMenu;
	  CATHSO				*_pHSO;
	  CATPSO				*_pPSO;

	  CATISpecObject_var    _spLeftEyePoint;
	  CATISpecObject_var    _spRightEyePoint;
	  CATISpecObject_var    _spGroundPlane;
	  CATLISTV(CATISpecObject_var) _ListOfObstacleBodies;
	  CATLISTP(CATBody)     _transientCGMBodies;
};

//----------------------------------------------------------------------

#endif
