// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPADVSAddin.h
// Provide implementation to interface
//    CATIAfrGeneralWksAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//IMPLEMENTATION
//    TIE: CATIAfrGeneralWksAddin

//End CAA2 Wizard Generation Report
//
//  Apr 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#ifndef TPADVSAddin_H
#define TPADVSAddin_H

#include "CATBaseUnknown.h"
#include "CATCmdContainer.h"


//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIAfrGeneralWksAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TPADVSAddin: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TPADVSAddin ();
     virtual ~TPADVSAddin ();

	void CreateCommands();
	CATCmdContainer * CreateToolbars();

  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TPADVSAddin (TPADVSAddin &);
  TPADVSAddin& operator=(TPADVSAddin&);

};

//-----------------------------------------------------------------------

#endif
