// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TPADVSFw
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Apr 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("TPACommonFW",Protected);
AddPrereqComponent("GeometricObjects",Protected);
AddPrereqComponent("VisualizationBase",Protected);
AddPrereqComponent("Visualization",Protected);
AddPrereqComponent("ObjectSpecsModeler",Protected);
AddPrereqComponent("GMModelInterfaces",Protected);