# COPYRIGHT Dassault Systemes 2026
#======================================================================
# Imakefile for module TPADVSAuto.m
#======================================================================
#
#  Apr 2026  Creation: Code generated by the CAA wizard  Praveen
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
 DI0PANV2 CATMathematics CATDialogEngine  \
ApplicationFrame CATAfrUUID 
# END WIZARD EDITION ZONE

LINK_WITH = TPACommonUtilityModule \
			CATGeometricObjects \
			JS0FM \
			CATViz \
			CATVisualization \
			TPADVSDialogModule \
			CATObjectSpecsModeler \
			CATGMModelInterfaces \
			$(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
