// COPYRIGHT Dassault Systemes 2024
//===================================================================
//
// TPACommonUtilityClass.h
// Header definition of TPACommonUtilityClass
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  May 2024  Creation: Code generated by the CAA wizard  Prasad
//===================================================================
#ifndef TPACommonUtilityClass_H
#define TPACommonUtilityClass_H

#include "TPACommonUtilityModule.h"
#include "CATBaseUnknown.h"
#include "CATISpecObject.h"
#include "CATIPrtContainer.h"
#include "CATIGSMFactory.h"
#include "CATLISTV_CATISpecObject.h"
#include "CATBody.h"
#include "CATPathElement.h"
#include "CATListOfCATCells.h"
#include "CATEdge.h"
#include "CATLISTP_CATMathPoint.h"
#include "CATFace.h"
#include "CAT3DBagRep.h"
#include "CAT3DCustomRep.h"
#include "CATSurface.h"
#include "CATPoint.h"
#include "CATGeoFactory.h"
#include "CATVertex.h"
#include "CATIGSMDirection.h"
#include "CATVertex.h"
#include "CATLISTP_CATMathVector.h"


#define VertexType "FEATUREFVERTEX"
#define EdgeType "FEATUREFVERTEX"
#define BorderEdgeType "FEATUREBORDERREDGE"
#define GSMBiDim "GSMBIDIM"
#define SpecObject "CATISpecObject"



//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href TPACommonUtilityClass constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new TPACommonUtilityClass;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByTPACommonUtilityModule TPACommonUtilityClass: public CATBaseUnknown
{
  CATDeclareClass;

  private:

  // Standard constructors and destructors
  // -------------------------------------
     TPACommonUtilityClass ();
public:
     virtual ~TPACommonUtilityClass ();
	 static TPACommonUtilityClass *GetClassObject();

	 CATISpecObject_var GetRootElement();

	 CATIPrtContainer_var GetPartContainer();

	 CATIGSMFactory_var GetGSMFactory();

	 CATGeoFactory_var GetPartGeoFactory();

	 HRESULT InsertFeature(CATISpecObject_var &ispFeature);

     CATListValCATISpecObject_var GetChildrensOfFeature(CATISpecObject_var &ispFeature, CATUnicodeString iusInterfaceName);

	 CATUnicodeString GetNameOfFeature(CATISpecObject_var &ispFeature);

	 CATBody_var GetBodyFromFeature(CATISpecObject_var &ispFeature);

	 CATPathElement *GetPathOfElement(CATISpecObject_var &ispFeature);

	 void GetTypeOfCurved(CATLISTP(CATCell) &listOfCells, int &nStraightLines, int &nCurves);

	 CATLISTP(CATMathPoint) CellTessellation(CATEdge *ipEdge);

	 HRESULT CreateDirectionOfFaceRep(CATFace *ipFace, CAT3DBagRep *&ip3DBagRep, CAT3DCustomRep *ip3DCustomRep, int inColorIndex);

	 CATLISTP(CATMathPoint) FaceTessellation(CATFace *ipFace);

	 CATMathPoint CalculateCenterPoint(CATLISTP(CATMathPoint) listOfPts);

	 CATMathPoint ProjectPointOnSurface(CATCell *ipFace, CATMathPoint impPoint, bool &obProjectSucceded);

	 bool ProjectPointOnSurface(CATMathPoint impPoint, CATSurface *ipSurface, CATPoint *ipPoint, CATGeoFactory *ipGeoFactory, CATMathDirection *ipDirection, CATMathPoint &ompProjectedPt);

	 CATMathDirection *GetNormalDirectionOfSurface(CATSurface *ipSurface);

	 CATMathVector GetNormalVectorOfSurface(CATSurface *ipSurface);

	 bool ProjectPointOnSurfaceNew(CATFace *ipFace, CATMathPoint impPoint, CATCell *ipSurface, CATPoint *ipPoint, CATGeoFactory *ipGeoFactory, CATMathDirection *ipDirection, CATMathPoint &ompProjectedPt, CATMathPoint &ompInputFaceCenterPt, double &odDistanceBtwSurfaces);

	 CATMathPoint ProjectPointOnSurfaceForWork(CATGeoFactory *ipGeoFactory, CATSurface *pSurface, CATMathPoint impPoint, bool &obProjectSucceded);

	 CATMathDirection *FindBestDirectionToProject(CATISpecObject_var &ispSurface);

	 double FindDistanceBetweenSurfaceBasedOnCenterPoint(CATCell *ipFirstSurface, CATCell *ipSecondSurface, CATGeoFactory *ipGeoFactory, CAT3DBagRep *&ip3DBagRepNew, bool &obFoundMinDistance, int &onNumberPtsOnSurface);

	 CATISpecObject_var ExtractFeature(const CATBaseUnknown_var& ispSelectedObject);

	 void FeaturizeTopologicalObject(CATCell *ipCell, CATBody_var &ispBody, CATISpecObject_var &ospSpecObject);

	 CATLISTV(CATISpecObject_var) GetDirectChildren(CATISpecObject_var &ispFeature);

	 HRESULT ReplacePointRelatedFeatures(CATISpecObject_var &ispOldSurface, CATISpecObject_var &ispFeature, CATISpecObject_var &ispReplacingSurface);

	 HRESULT ReplaceLineRelatedFeatures(CATISpecObject_var &ispOldSurface, CATISpecObject_var &ispFeature, CATISpecObject_var &ispReplacingSurface);

	 CATISpecObject_var FindValidEdgeForReplace(CATISpecObject_var &ispCurrentEdge, CATISpecObject_var &ispNewFeature);

	 CATIGSMDirection_var FindValidEdgeForDirectionReplace(CATIGSMDirection_var &ispGSMDirection, CATISpecObject_var &ispNewFeature);

	 CATISpecObject_var FindValidPointForReplace(CATISpecObject_var &ispCurrentVertex, CATISpecObject_var &ispNewFeature);

	 void GetPointsFromEdge(CATEdge *ipEdge, CATMathPoint &mpFirstPoint, CATMathPoint &mpSecondPoint);

	 HRESULT ReplaceAssembleRelatedFeature(CATISpecObject_var &ispChildren, CATISpecObject_var &ispOldFeature, CATISpecObject_var &ispNewFeature);

	 HRESULT ReplaceOffsetRelatedFeature(CATISpecObject_var &ispChildren, CATISpecObject_var &ispNewFeature);

	 HRESULT ReplaceExtrudeRelatedFeature(CATISpecObject_var &ispChildren, CATISpecObject_var &ispNewFeature);

	 HRESULT ReplaceExtraplatedRelatedFeature(CATISpecObject_var &ispChildren, CATISpecObject_var &ispOldFeature, CATISpecObject_var &ispNewFeature);

	 CATMathPoint GetPointFromVertex(CATVertex *ipVertex);

	 CATISpecObject_var FindValidCircularEdgeForReplace(CATISpecObject_var &ispCurrentEdge, CATISpecObject_var &ispNewFeature);

	 HRESULT ReplacePlaneRelatedFeature(CATISpecObject_var &ispChildren, CATISpecObject_var &ispOldFeature, CATISpecObject_var &ispNewFeature);

	 HRESULT ReplaceProjectionRelatedFeature(CATISpecObject_var &ispChildren, CATISpecObject_var &ispOldSurface, CATISpecObject_var &ispNewFeature);

	 HRESULT ReplaceBoundaryRelatedFeature(CATISpecObject_var &ispChildren, CATISpecObject_var &ispOldSurface, CATISpecObject_var &ispNewFeature);

	 HRESULT ReplaceSplitRelatedFeature(CATISpecObject_var &ispChildren, CATISpecObject_var &ispOldSurface, CATISpecObject_var &ispNewFeature);

	 void CreateRepAsPerReplaceCommand(CATISpecObject_var &ispOldSurface, CATISpecObject_var &ispNewSurface, CAT3DBagRep *&ipCreatedViewerOld);

	 double RoundToSingleDecimal(double var);

	 double  RoundToZeroDecimal(double var);

	CATBaseUnknown_var FindElementByName(CATBaseUnknown_var &ispBaseElt, CATUnicodeString iusFeatName);

	CATVertex_var FindEyeContactPoint(CATBaseUnknown_var &ispFirstDir, CATBaseUnknown_var &ispSecondDir);

	CATMathVector ComputeDirection(double theta_deg, double phi_deg);

	CATMathVector ComputeDirectionLocal(const CATMathVector& viewDir, double theta_deg, double phi_deg);

	CATMathVector GetDirectionOfStraightEdge(CATBaseUnknown_var &ispStraightLine);

	CATMathVector ComputeDirectionLocalUpdated(const CATMathVector& forward, const CATMathVector& right, const CATMathVector& up, double theta_deg, double phi_deg);

	HRESULT GetMathPointFromFeature(CATBaseUnknown_var &ispBaseUnkown, CATMathPoint &ompMathPoint);

	CATLISTP(CATMathVector) GenerateDirections(const CATMathVector& mainDir, const CATMathVector& rotationAxis, double leftAngleDeg, double rightAngleDeg, double stepDeg);
	CATMathVector RotateVector(
    const CATMathVector& vec,
    const CATMathVector& axis,
    double angleDeg);
  // Copy constructor and equal operator
  // -----------------------------------
  TPACommonUtilityClass (TPACommonUtilityClass &);
  TPACommonUtilityClass& operator=(TPACommonUtilityClass&);

};

//-----------------------------------------------------------------------

#endif
