// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TPAGeneralFw
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Feb 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("PartInterfaces",Protected);
AddPrereqComponent("CATGSMUseItf",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("MechanicalModelerUI",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("ObjectSpecsModeler",Protected);
AddPrereqComponent("TPACommonFW",Protected);
AddPrereqComponent("SketcherInterfaces",Protected);
AddPrereqComponent("MecModInterfaces",Protected);
AddPrereqComponent("KnowledgeInterfaces",Protected);
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("GSMInterfaces",Protected);
AddPrereqComponent("DraftingInterfaces",Protected);
AddPrereqComponent("InteractiveInterfaces",Protected);
AddPrereqComponent("GMModelInterfaces",Protected);
AddPrereqComponent("GeometricObjects",Protected);
AddPrereqComponent("MeasureGeometryInterfaces",Protected);
AddPrereqComponent("SpaceAnalysisInterfaces",Protected);
AddPrereqComponent("VisualizationBase",Protected);
AddPrereqComponent("Visualization",Protected);
