# COPYRIGHT Dassault Systemes 2026
#======================================================================
# Imakefile for module TPAAutoDrawingModule.m
#======================================================================
#
#  Feb 2026  Creation: Code generated by the CAA wizard  Praveen
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0GROUP JS0FM CATMathematics CATDialogEngine 
# END WIZARD EDITION ZONE

LINK_WITH = CATDialogEngine \
			CATApplicationFrame \
			DI0PANV2 \
			TPACommonUtilityModule \
			CATObjectSpecsModeler \
			CATSketcherInterfaces \
			CATMecModInterfaces \
			KnowledgeItf  \
			CATObjectModelerBase \
			CATGitInterfaces \
			CATPartInterfaces \
			CATDraftingInterfaces \
			CATInteractiveInterfaces \
			CATGMModelInterfaces \
			CATCGMGeoMath \
			CATSaiSpaceAnalysisItf \	
			CATViz \
			CATVisualization \
			$(WIZARD_LINK_MODULES)
			

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
