// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPAAutoDrawingCmd.h
// The state chart based command: TPAAutoDrawingCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Feb 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#ifndef TPAAutoDrawingCmd_H
#define TPAAutoDrawingCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CATDlgFile.h"
#include "CATISpecObject.h"



//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class TPAAutoDrawingCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TPAAutoDrawingCmd, CATStateCommand )

  public:

  TPAAutoDrawingCmd();
  virtual ~TPAAutoDrawingCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  CreateDrawingAndViews();
  void CreateAutoDimensions();
  void AssignThicknessAndColor(CATISpecObject_var &ispFeature, int nRed, int nGreen, int nBlue);
  void ReadJSONAndCreatePart(CATUnicodeString iusFileName);
  void OpenOKCB(CATCommand          *iPublishingCommand, 
                          CATNotification     *iNotification, 
                          CATCommandClientData iUsefulData);
  void OpenCANCELCB(CATCommand          *iPublishingCommand, 
                          CATNotification     *iNotification, 
                          CATCommandClientData iUsefulData);

  private:
	 CATDlgFile			*_pDlgFile;
	
};

//----------------------------------------------------------------------

#endif
