// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPADVSDirectView3DDlg.h
// The dialog : TPADVSDirectView3DDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  May 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#ifndef TPADVSDirectView3DDlg_H
#define TPADVSDirectView3DDlg_H

#include "TPADVSDialogModule.h"
#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class ExportedByTPADVSDialogModule TPADVSDirectView3DDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TPADVSDirectView3DDlg, CATDlgDialog )

  public:

  TPADVSDirectView3DDlg();
  virtual ~TPADVSDirectView3DDlg();

  void Build ();

  CATDlgSpinner* GetRangeSpinner(){return _SpinnerRange;}
  CATDlgSlider* GetSliderAccuracry(){return _SliderAccuracy;}

  CATDlgMultiList* GetVehicleGeometryMultiList(){return     _MulitListVehicleGeometry;}

  CATDlgEditor* GetGroundPlaneEditor(){return _EditorGroundPlane;}
  CATDlgCombo* GetStandardCombo(){return _ComboStandard;}
  CATDlgRadioButton* GetRadioButtGenFromAHP(){return _RadioButtGenFromAHP;}
  CATDlgRadioButton* GetRadioButtSelectDirectly(){return _RadioButtSelectDirectly;}
  CATDlgEditor* GetAccelKeyPtEditor(){return _EditorAccelKeyPt;}
  CATDlgEditor* GetSeatMidPtEditor(){return _EditorSeatMidPt;}
  CATDlgSpinner* GetLengthOffsetSpinner(){return _SpinnerLengthOffset;}
  CATDlgEditor* GetLeftEyeEditor(){return _EditorLeftEye;}
  CATDlgEditor* GetMidEyeEditor(){return _EditorMidEye;}
  CATDlgEditor* GetRightEyeEditor(){return _EditorRightEye;}
  CATDlgSpinner* GetNeckPivotSpinner(){return _SpinnerNeckPivot;}
  CATDlgSpinner* GetHeadRotationSpinner(){return _SpinnerHeadRotation;}
  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _FrmDefinition;
 CATDlgFrame*      _FrmDefinitionInputs;
 CATDlgLabel*      _LblBaseData;
 CATDlgLabel*      _LblStandard;
 CATDlgLabel*      _LblLoading;
 CATDlgSelectorList*      _SelListBaseData;
 CATDlgSelectorList*      _SelListStandard;
 CATDlgSelectorList*      _SelListLoading;
 CATDlgCheckButton*      _CheckButtFree;
 CATDlgFrame*      _FrmDefinitionUse;
 CATDlgRadioButton*      _RadioButtUseStandardEyes;
 CATDlgRadioButton*      _RadioButtUseV5Pts;
 CATDlgRadioButton*      _RadioButtUseMultipleEyes;
 CATDlgFrame*      _Frame007;
 CATDlgTabContainer*      _TabContainer008;
 CATDlgTabPage*      _FirstPage;
 CATDlgFrame*      _FrmView;
 CATDlgFrame*      _Frame019;
 CATDlgLabel*      _LblRange;
 CATDlgSpinner*      _SpinnerRange;
 CATDlgLabel*      _LablComputation;
 CATDlgCombo*      _Combo022;
 CATDlgFrame*      _Frame020;
 CATDlgLabel*      _LblOrientation;
 CATDlgCombo*      _ComboOrientation;
 CATDlgSpinner*      _SpinnerOrientationDegree;
 CATDlgFrame*      _FrmTargetSurface;
 CATDlgFrame*      _Frame029;
 CATDlgLabel*      _LblTypeTargetSurface;
 CATDlgCombo*      _Combo028;
 CATDlgEditor*      _EditorTargetSurfaceTypeValue;
 CATDlgFrame*      _Frame030;
 CATDlgCheckButton*      _CheckButtVisualizeTargetSurface;
 CATDlgFrame*      _FrmSelSurface;
 CATDlgFrame*      _Frame033;
 CATDlgLabel*      _LblSurface;
 CATDlgEditor*      _EditorSurface;
 CATDlgPushButton*      _PushButtCGR;
 CATDlgFrame*      _Frame037;
 CATDlgCheckButton*      _CheckButtVisuaSelSurface;
 CATDlgFrame*      _FrmDiscretization;
 CATDlgLabel*      _LblDiscretization;
 CATDlgLabel*      _LblAccurate;
 CATDlgFrame*      _FrmUserSelInput;
 CATDlgTabContainer*      _TabContainer039;
 CATDlgTabPage*      _TabVehicleGeometry;
 CATDlgMultiList*      _MulitListVehicleGeometry;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
  CATDlgSlider*	   _SliderAccuracy;
  CATDlgFrame*         _FrmVolumetric;
  CATDlgLabel*         _LblComplianceStandard;
  CATDlgCombo*         _ComboStandard;
  CATDlgLabel*         _LblGroundPlane;
  CATDlgEditor*        _EditorGroundPlane;

  CATDlgRadioButton*   _RadioButtGenFromAHP;
  CATDlgRadioButton*   _RadioButtSelectDirectly;

  CATDlgLabel*         _LblAccelKeyPt;
  CATDlgEditor*        _EditorAccelKeyPt;
  CATDlgLabel*         _LblSeatMidPt;
  CATDlgEditor*        _EditorSeatMidPt;
  CATDlgLabel*         _LblLengthOffset;
  CATDlgSpinner*       _SpinnerLengthOffset;

  CATDlgLabel*         _LblLeftEye;
  CATDlgEditor*        _EditorLeftEye;
  CATDlgLabel*         _LblMidEye;
  CATDlgEditor*        _EditorMidEye;
  CATDlgLabel*         _LblRightEye;
  CATDlgEditor*        _EditorRightEye;

  CATDlgLabel*         _LblNeckPivot;
  CATDlgSpinner*       _SpinnerNeckPivot;
  CATDlgLabel*         _LblHeadRotation;
  CATDlgSpinner*       _SpinnerHeadRotation;
};

//----------------------------------------------------------------------

#endif
