// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPAAutoDrawingCmd.cpp
// The state chart based command: TPAAutoDrawingCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Feb 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#include "TPAAutoDrawingCmd.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
#include "CATApplicationFrame.h"
#include <iostream>
#include <fstream>
#include <string>
#include "CATISpecObject.h"
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"
#include "CATMathPoint.h"
#include "CATLISTP_CATMathPoint.h"
#include "CATISketchFactory.h"
#include "CATIPrtPart.h"
#include "CATLISTV_CATISpecObject.h"
#include "Json.h"
#include "CATListOfDouble.h"
#include <sstream>
#include "TPACommonUtilityClass.h"
#include "CATISketch.h"
#include "CATI2DWFFactory.h"
#include "CATListOfInt.h"
#include "CATI2DCurve.h"
#include "CATI2DPoint.h"
#include "CATICkeParmFactory.h"
#include "CATICkeParm.h"
#include "CATIGSMFactory.h"
#include "CATIPrtFactory.h"
#include "CATIShaft.h"
#include "CATIPartRequest.h"
#include "CATIPrtProceduralView.h"
#include "CATDocument.h"
#include "CATIIniInteractiveSession.h"
#include "CATSession.h"
#include "CATIEditor.h"
#include "CATFrmEditor.h"
#include "CATIDftDrawing.h"
#include "CATIDftDocumentServices.h"
#include "CATIContainer.h"
#include "CATIDftStandardManager.h"
#include "CATIStringList.h"
#include "CATIDftDrawingFormats.h"
#include "CATIDftFormat.h"
#include "CATIDftSheet.h"
#include "CATIDftSheetFormat.h"
#include "CATIADrawingSheet.h"
#include "CATIADrawingViews.h"
#include "CATIADrawingView.h"
#include "CATIAGenerativeViewBehavior.h"
#include "CATIABase.h"
#include "CATIView.h"
#include "CATIUnknownList.h"
#include "CATISheet.h"
#include "CATIDftView.h"
#include "CATIDftGenView.h"
#include "CATIDrwAnnotationFactory.h"
#include "CATIDftGenGeomAccess.h"
#include "IDMLine2D.h"
#include "CATIDrwDimDimension.h"
#include "CATLISTPIUnknown.h"
#include "CATIUnknownListImpl.h"
#include "CATDimDefinition.h"
#include "IDMCircle2D.h"
#include "CATListOfCATCells.h"
#include "CATINewHole.h"
#include "CATGetEnvValue.h"
#include "CATIMeasurableInContext.h"
#include "CATMathPoint2D.h"
#include "CATIDrwDimDimensionLine.h"
#include "CATGraphicAttributeSet.h"
#include "CATIDrwDimValue.h"
#include "CATIDrwProperties.h"
#include "CATIVisProperties.h"
#include "CATVisPropertiesValues.h"
#include "CATIModelEvents.h"
#include "CATModifyVisProperties.h"
#include "CATIDrwDimValueComponent.h"
#include "CATIDrwDimFormat.h"










CATCreateClass( TPAAutoDrawingCmd);


using namespace std;
//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
TPAAutoDrawingCmd::TPAAutoDrawingCmd() :
  CATStateCommand ("TPAAutoDrawingCmd", CATDlgEngOneShot, CATCommandModeShared) 
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
{
	_pDlgFile = NULL;
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
TPAAutoDrawingCmd::~TPAAutoDrawingCmd()
{
	if(NULL != _pDlgFile)
	{
		_pDlgFile->RequestDelayedDestruction();
	}
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void TPAAutoDrawingCmd::BuildGraph()
{
	/*_pDlgFile = new CATDlgFile((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(), "TPA JSON File Selection", CATDlgFileMultisel);
    CATUnicodeString nameExtension   = CATUnicodeString("JSON File (*.json)");
  CATString        filterExtension = CATString("*.json");
  _pDlgFile->SetFilterStrings(&nameExtension, &filterExtension, 1);
  _pDlgFile->SetVisibility(CATDlgShow);
  AddAnalyseNotificationCB(_pDlgFile, 
                           _pDlgFile->GetDiaOKNotification(), 
		           (CATCommandMethod)& TPAAutoDrawingCmd::OpenOKCB,
                            NULL);
   AddAnalyseNotificationCB(_pDlgFile, 
                           _pDlgFile->GetDiaCANCELNotification(), 
		           (CATCommandMethod)& TPAAutoDrawingCmd::OpenCANCELCB,
                            NULL);*/
	CreateDrawingAndViews();
}


//-------------------------------------------------------------------------
// CreateDrawingAndViews ()
//-------------------------------------------------------------------------
CATBoolean TPAAutoDrawingCmd::CreateDrawingAndViews()
{
	CATDocument *pDocument = CATFrmEditor::GetCurrentEditor()->GetDocument();
	if(NULL == pDocument)
		return CATFalse;;
	CATILinkableObject_var spLinkable = pDocument;
	if(!spLinkable)
		return CATFalse;;
	CATSession *pSession = CATSession::GetPtrSession();
	if(NULL == pSession)
		return CATFalse;;
	CATIIniInteractiveSession * piInteractiveSession = NULL;
	pSession->QueryInterface(IID_CATIIniInteractiveSession, (void **) &piInteractiveSession);
	if(NULL == piInteractiveSession)
		return CATFalse;
	char *opDirect = NULL;
	::CATGetEnvValue("TEMP", &opDirect);
	if(NULL == opDirect)
		return CATFalse;
	CATUnicodeString usPath(opDirect);
	usPath.ReplaceAll("\\", "\\\\");
	usPath = usPath + "\\\\" + "DrawingTemplate.CATDrawing";
	CATIEditor *oCreatedEditor = NULL;
	//piInteractiveSession->NewFrom("E:\\Prasad\\TPA\\CATIA\\NXCATIAMigration\\Parts\\DrawingTemplate.CATDrawing", &oCreatedEditor);
	piInteractiveSession->NewFrom(usPath, &oCreatedEditor);
	if(NULL == oCreatedEditor)
		return CATFalse;;
	CATFrmEditor *pEditor = oCreatedEditor->GetEditor();
	if(NULL == pEditor)
		return CATFalse;;
	CATDocument *pDoc = pEditor->GetDocument();
	if(NULL == pDoc)
		return CATFalse;;
	CATIDftDrawing *piDftDrawing = NULL;
	CATIDftDocumentServices *piDftDocServices = NULL;
	CATIContainer_var spDrwCont;
	if (SUCCEEDED(pDoc->QueryInterface(IID_CATIDftDocumentServices, (void **)&piDftDocServices)))
	{
		if (SUCCEEDED(piDftDocServices->GetDrawing(IID_CATIDftDrawing, (void **)&piDftDrawing)))
		{
			if (piDftDrawing)
			{
				// Gets the drawing container
				CATISpecObject *piSpecObj=NULL;
				if (SUCCEEDED(piDftDrawing->QueryInterface(IID_CATISpecObject,(void **)&piSpecObj)))
				{
					spDrwCont = piSpecObj->GetFeatContainer();
					piSpecObj->Release();
					piSpecObj=NULL;
				}
			}
		}
		piDftDocServices->Release();
		piDftDocServices=NULL;
	}

	// No drawing container found.   
	if (NULL_var == spDrwCont || !piDftDrawing)
	{
		return CATFalse;;
	}

	// Adds the format to the current sheet.
	CATIDftSheet *piDftSheet = NULL;
	CATIDftSheetFormat *piDftSheetFormat = NULL;
	double dScale = 1.0;
	CATIDftSheet *piDftNewSheet = NULL;
	wchar_t *pSheetName= L"TPASheet";
	if (SUCCEEDED(piDftDrawing->AddSheet(&piDftNewSheet,pSheetName)))
	{
		CATIADrawingSheet *piCATIADrawingSheet = NULL;
		piDftNewSheet->QueryInterface(IID_CATIADrawingSheet, (void**)&piCATIADrawingSheet);
		if (NULL != piCATIADrawingSheet)
		{
			CATIADrawingViews *listOfViews = NULL;
			piCATIADrawingSheet->get_Views(listOfViews);
			if (NULL != listOfViews)
			{
				CATUnicodeString usDetailName = "AutomaticNaming";
				//usDetailName += ".1";
				BSTR bstrDetail;
				usDetailName.ConvertToBSTR(&bstrDetail);
				CATIADrawingView *opDrawingViewCreated;
				listOfViews->Add(bstrDetail, opDrawingViewCreated);
				if (NULL != opDrawingViewCreated)
				{
					CATISpecObject_var spSpecView = opDrawingViewCreated;
					if (!!spSpecView)
					{
						CATIView_var spView = spSpecView;
						if(!!spView)
						{
							spView->SetViewType(FrontView);
						}
					}
					CATIAGenerativeViewBehavior *opGenViewBehaviorFrontView = NULL;
					opDrawingViewCreated->get_GenerativeBehavior(opGenViewBehaviorFrontView);
					if(NULL != opGenViewBehaviorFrontView)
					{
						CATIABase *opBase = NULL;
						pDocument->QueryInterface(IID_CATIABase, (void**)&opBase);
						if(NULL != opBase)
						{
							opGenViewBehaviorFrontView->put_HiddenLineMode(catHlrModeOn);
							HRESULT hr = opGenViewBehaviorFrontView->put_Document(opBase);
							opDrawingViewCreated->put_Scale(dScale);
							opDrawingViewCreated->put_x(430);
							opDrawingViewCreated->put_y(300);
							opGenViewBehaviorFrontView->Update();
							CATIAGenerativeViewLinks *opFrontViewGenrativeLinks = NULL;
							opDrawingViewCreated->get_GenerativeLinks(opFrontViewGenrativeLinks);
							if(NULL != opFrontViewGenrativeLinks)
							{
								{
									CATIADrawingView *opDrawingViewCreatedLeftView;
									listOfViews->Add(bstrDetail, opDrawingViewCreatedLeftView);
									if(NULL != opDrawingViewCreatedLeftView)
									{
										CATIAGenerativeViewBehavior *opGenViewBehaviorLeftView = NULL;
										opDrawingViewCreatedLeftView->get_GenerativeBehavior(opGenViewBehaviorLeftView);
										if(NULL != opGenViewBehaviorLeftView)
										{
											hr = opGenViewBehaviorLeftView->DefineProjectionView(opGenViewBehaviorFrontView, catLeftView);
											if(SUCCEEDED(hr))
											{
												CATIAGenerativeViewLinks *opLeftViewGenrativeLinks = NULL;
												opDrawingViewCreatedLeftView->get_GenerativeLinks(opLeftViewGenrativeLinks);
												if(NULL != opLeftViewGenrativeLinks)
												{
													hr = opFrontViewGenrativeLinks->CopyLinksTo(opLeftViewGenrativeLinks);
													if(SUCCEEDED(hr))
													{
														opDrawingViewCreatedLeftView->put_Scale(dScale);
														opDrawingViewCreatedLeftView->put_x(250);
														opDrawingViewCreatedLeftView->put_y(300);
														opGenViewBehaviorLeftView->put_HiddenLineMode(catHlrModeOn);
														opGenViewBehaviorLeftView->Update();
													}
												}
											}
										}
									}
								}
								{
									CATIADrawingView *opDrawingViewCreatedBottomView;
									listOfViews->Add(bstrDetail, opDrawingViewCreatedBottomView);
									if(NULL != opDrawingViewCreatedBottomView)
									{
										CATIAGenerativeViewBehavior *opGenViewBehaviorBottomView = NULL;
										opDrawingViewCreatedBottomView->get_GenerativeBehavior(opGenViewBehaviorBottomView);
										if(NULL != opGenViewBehaviorBottomView)
										{
											hr = opGenViewBehaviorBottomView->DefineProjectionView(opGenViewBehaviorFrontView, catBottomView);
											if(SUCCEEDED(hr))
											{
												CATIAGenerativeViewLinks *opBottomViewGenrativeLinks = NULL;
												opDrawingViewCreatedBottomView->get_GenerativeLinks(opBottomViewGenrativeLinks);
												if(NULL != opBottomViewGenrativeLinks)
												{
													hr = opFrontViewGenrativeLinks->CopyLinksTo(opBottomViewGenrativeLinks);
													if(SUCCEEDED(hr))
													{
														opDrawingViewCreatedBottomView->put_Scale(dScale);
														opDrawingViewCreatedBottomView->put_x(425);
														opDrawingViewCreatedBottomView->put_y(80);
														opGenViewBehaviorBottomView->put_HiddenLineMode(catHlrModeOn);
														opGenViewBehaviorBottomView->Update();
													}
												}
											}
										}
									}
								}
								{
									CATIADrawingView *opDrawingViewCreatedRightView;
									listOfViews->Add(bstrDetail, opDrawingViewCreatedRightView);
									if(NULL != opDrawingViewCreatedRightView)
									{
										CATIAGenerativeViewBehavior *opGenViewBehaviorRightSideView = NULL;
										opDrawingViewCreatedRightView->get_GenerativeBehavior(opGenViewBehaviorRightSideView);
										if(NULL != opGenViewBehaviorRightSideView)
										{
											hr = opGenViewBehaviorRightSideView->DefineProjectionView(opGenViewBehaviorFrontView, catRightView);
											if(SUCCEEDED(hr))
											{
												CATIAGenerativeViewLinks *opRightSideViewGenrativeLinks = NULL;
												opDrawingViewCreatedRightView->get_GenerativeLinks(opRightSideViewGenrativeLinks);
												if(NULL != opRightSideViewGenrativeLinks)
												{
													hr = opFrontViewGenrativeLinks->CopyLinksTo(opRightSideViewGenrativeLinks);
													if(SUCCEEDED(hr))
													{
														opDrawingViewCreatedRightView->put_Scale(dScale);
														opDrawingViewCreatedRightView->put_x(600);
														opDrawingViewCreatedRightView->put_y(300);
														opGenViewBehaviorRightSideView->put_HiddenLineMode(catHlrModeOn);
														opGenViewBehaviorRightSideView->Update();
													}
												}
											}
										}
									}
								}
								{
									CATIADrawingView *opDrawingViewCreatedTopView;
									listOfViews->Add(bstrDetail, opDrawingViewCreatedTopView);
									if(NULL != opDrawingViewCreatedTopView)
									{
										CATIAGenerativeViewBehavior *opGenViewBehaviorTopView = NULL;
										opDrawingViewCreatedTopView->get_GenerativeBehavior(opGenViewBehaviorTopView);
										if(NULL != opGenViewBehaviorTopView)
										{
											hr = opGenViewBehaviorTopView->DefineProjectionView(opGenViewBehaviorFrontView, catTopView);
											if(SUCCEEDED(hr))
											{
												CATIAGenerativeViewLinks *opTopSideViewGenrativeLinks = NULL;
												opDrawingViewCreatedTopView->get_GenerativeLinks(opTopSideViewGenrativeLinks);
												if(NULL != opTopSideViewGenrativeLinks)
												{
													hr = opFrontViewGenrativeLinks->CopyLinksTo(opTopSideViewGenrativeLinks);
													if(SUCCEEDED(hr))
													{
														opDrawingViewCreatedTopView->put_Scale(dScale);
														opDrawingViewCreatedTopView->put_x(425);
														opDrawingViewCreatedTopView->put_y(500);
														opGenViewBehaviorTopView->put_HiddenLineMode(catHlrModeOn);
														opGenViewBehaviorTopView->Update();
													}
												}
											}
										}
									}
								}
								{
									CATIADrawingView *opDrawingViewCreatedRearView;
									listOfViews->Add(bstrDetail, opDrawingViewCreatedRearView);
									if(NULL != opDrawingViewCreatedRearView)
									{
										CATIAGenerativeViewBehavior *opGenViewBehaviorRearView = NULL;
										opDrawingViewCreatedRearView->get_GenerativeBehavior(opGenViewBehaviorRearView);
										if(NULL != opGenViewBehaviorRearView)
										{
											hr = opGenViewBehaviorRearView->DefineProjectionView(opGenViewBehaviorFrontView, catRearView);
											if(SUCCEEDED(hr))
											{
												CATIAGenerativeViewLinks *opRearSideViewGenrativeLinks = NULL;
												opDrawingViewCreatedRearView->get_GenerativeLinks(opRearSideViewGenrativeLinks);
												if(NULL != opRearSideViewGenrativeLinks)
												{
													hr = opFrontViewGenrativeLinks->CopyLinksTo(opRearSideViewGenrativeLinks);
													if(SUCCEEDED(hr))
													{
														opDrawingViewCreatedRearView->put_Scale(dScale);
														opDrawingViewCreatedRearView->put_x(760);
														opDrawingViewCreatedRearView->put_y(300);
														opGenViewBehaviorRearView->put_HiddenLineMode(catHlrModeOn);
														opGenViewBehaviorRearView->Update();
													}
												}
											}
										}
									}
								}
								{
									CATIADrawingView *opDrawingViewCreatedIsoView;
									listOfViews->Add(bstrDetail, opDrawingViewCreatedIsoView);
									if(NULL != opDrawingViewCreatedIsoView)
									{
										CATIAGenerativeViewBehavior *opGenViewBehaviorIsoView = NULL;
										opDrawingViewCreatedIsoView->get_GenerativeBehavior(opGenViewBehaviorIsoView);
										if(NULL != opGenViewBehaviorIsoView)
										{
											opGenViewBehaviorIsoView->put_Document(opBase);
											hr = opGenViewBehaviorIsoView->DefineIsometricView(-0.018879, 0.991943, 0.12527, -0.001182, -0.125314, 0.992116);
											if(SUCCEEDED(hr))
											{
												opDrawingViewCreatedIsoView->put_Scale(dScale);
												opDrawingViewCreatedIsoView->put_x(670);
												opDrawingViewCreatedIsoView->put_y(500);
												opGenViewBehaviorIsoView->put_HiddenLineMode(catHlrModeOn);
												opGenViewBehaviorIsoView->Update();
											}
										}
									}
								}
							}
							opBase->Release();
							opBase = NULL;
						}
					}

				}
			}
		}
		CreateAutoDimensions();
	}
	return TRUE;
}

//-------------------------------------------------------------------------
// TPAAutoDrawingCmd::CreateAutoDimensions()
//-------------------------------------------------------------------------
void TPAAutoDrawingCmd::CreateAutoDimensions()
{
	CATTry
	{
		CATDocument *pDocument = CATFrmEditor::GetCurrentEditor()->GetDocument();
		if(NULL == pDocument)
			return;
		CATIDftDrawing *piDftDrawing = NULL;
		CATIDftDocumentServices *piDftDocServices = NULL;
		CATIContainer_var spDrwCont;
		HRESULT rc = pDocument->QueryInterface(IID_CATIDftDocumentServices, (void **)&piDftDocServices);
		if (FAILED(rc) || NULL == piDftDocServices)
			return;
		rc = piDftDocServices->GetDrawing(IID_CATIDftDrawing, (void **)&piDftDrawing);
		piDftDocServices->Release();
		piDftDocServices = NULL;
		if (FAILED(rc) || NULL == piDftDrawing)
			return;
		CATISpecObject *piSpecObj = NULL;
		rc = piDftDrawing->QueryInterface(IID_CATISpecObject, (void **)&piSpecObj);
		if (FAILED(rc) || NULL == piSpecObj)
			return;
		spDrwCont = piSpecObj->GetFeatContainer();
		piSpecObj->Release();
		piSpecObj = NULL;
		if (!spDrwCont)
			return;
		CATIUnknownList *opListOfSheets = NULL;
		piDftDrawing->GetSheets(&opListOfSheets);
		if (NULL == opListOfSheets)
			return;
		unsigned int nSheetCount;
		opListOfSheets->Count(&nSheetCount);
		for (size_t i = 0; i < nSheetCount; i++)
		{
			CATISheet *piSheet = NULL;
			IUnknown *oUnknownSheet = NULL;
			opListOfSheets->Item(i, &oUnknownSheet);
			if (NULL == oUnknownSheet)
				continue;
			oUnknownSheet->QueryInterface(IID_CATISheet, (void**)&piSheet);
			if (NULL == piSheet)
				continue;
			CATIAlias *piAlias = NULL;
			piSheet->QueryInterface(IID_CATIAlias, (void**)&piAlias);
			if (NULL == piAlias)
				continue;
			CATUnicodeString usSheetName = piAlias->GetAlias();
			if (usSheetName.SearchSubString("Detail") >= 0)
				continue;
			CATLISTV(CATISpecObject_var) listOfViews = piSheet->GetViewList();
			if(listOfViews.Size() == 0)
				continue;
			CATLISTV(CATISpecObject_var) listOfViewsSpec;
			for (size_t j = 3; j <= listOfViews.Size(); j++)
			{
				CATBoolean bDimControl = CATFalse;
				CATBoolean bDimControlCircle = CATFalse;
				CATIDftView_var spDftView = listOfViews[j];
				if (!spDftView)
					continue;
				CATIUnknownList *opListOfCenterLines = NULL;
				spDftView->GetComponents(IID_CATIDrwCenterLine, &opListOfCenterLines);
				if(NULL != opListOfCenterLines)
				{
					unsigned int onCount;
					opListOfCenterLines->Count(&onCount);
					int kjk = 1;
				}
				spDftView->Activate();
				CATI2DWFFactory_var sp2DWFFactory = listOfViews[j];
				if(!sp2DWFFactory)
					continue;
				wchar_t *opViewName = NULL;
				spDftView->GetViewName(&opViewName);
				if(NULL == opViewName)
					continue;
				CATUnicodeString usViewName;
				usViewName.BuildFromWChar(opViewName);
				if(usViewName.SearchSubString("Iso") >= 0)
					continue;
				CATIDrwAnnotationFactory_var spAnnoFactory = spDftView;
				if(!spAnnoFactory)
					continue;
				IUnknown *piGenView = NULL;
				spDftView->GetApplicativeExtension(IID_CATIDftGenView, &piGenView);
				if (piGenView != NULL)
				{
					CATIDftGenGeomAccess *piGenGeomAccess = NULL;
					rc = piGenView->QueryInterface(IID_CATIDftGenGeomAccess, (void**)& piGenGeomAccess);
					if (SUCCEEDED(rc))
					{
						CATIUnknownList * piList = NULL;
						//Get a list containing all Generated Geometry of the view.
						rc = piGenGeomAccess->GetAllGeneratedItems(IID_CATISpecObject, &piList);
						if (SUCCEEDED(rc))
						{
							unsigned int piListSize = 0;
							piList->Count(&piListSize);
							CATLISTP(IUnknown) listOfStraightGeometry;
							CATLISTP(IUnknown) lsitOfCurveGeometry;
							for(int nGenItr = 0; nGenItr < piListSize; ++nGenItr)
							{
								IUnknown *opSingleGenItem = NULL;
								piList->Item(nGenItr, &opSingleGenItem);
								if (NULL != opSingleGenItem)
								{
									IDMCurve2D *piCurve2D = NULL;
									opSingleGenItem->QueryInterface(IID_IDMCurve2D, (void**)&piCurve2D);
									if(NULL != piCurve2D)
									{
										double dStartPt[2], dEndPt[2];
										piCurve2D->GetEndPoints(dStartPt, dEndPt);
										CATMathPoint2D mpStartPt(dStartPt[0], dStartPt[1]);
										CATMathPoint2D mpEndPt(dEndPt[0], dEndPt[1]);
										double ddLenDia = mpStartPt.DistanceTo(mpEndPt);
										IDMCircle2D *piIDMCircle2D = NULL;
										opSingleGenItem->QueryInterface(IID_IDMCircle2D, (void**)&piIDMCircle2D);
										if(NULL != piIDMCircle2D)
										{
											lsitOfCurveGeometry.Append(opSingleGenItem);
											{
												double dCurveRadius = 0.0;
												if(ddLenDia > 300 || ddLenDia < 60)
												{
													CATIUnknownList * piSelectionsList = NULL;
													CATIUnknownListImpl * piListsel = new CATIUnknownListImpl();
													piSelectionsList = (CATIUnknownList*)piListsel;
													double dStartPoint[2];
													double dEndPoint[2];
													dStartPoint[0] = 0.0;
													dStartPoint[1] = 5.0;
													dEndPoint[0] = 50.0;
													dEndPoint[1] = 5.0;
													double  * pts[2] = { dStartPoint, dEndPoint };
													{
														piSelectionsList->Add(0, opSingleGenItem);
														CATDrwDimType dimType;
														dimType = DrwDimDiameter;
														CATDimDefinition dimDef;
														dimDef.Orientation = DrwDimAuto;
														CATIDrwDimDimension * piDimHoriz = NULL;
														if(bDimControlCircle == CATFalse)
														{
															HRESULT rc = spAnnoFactory->CreateDimension(piSelectionsList, pts, dimType, &dimDef, &piDimHoriz);
															if (NULL != piDimHoriz)
															{
																rc = piDimHoriz->SetAutoMode(2);
																rc = piDimHoriz->SetInOutMode(2);
																//bDimControlCircle = CATTrue;
																CATIDrwDimValue_var spDrwValue = piDimHoriz->GetValue();
																if (!!spDrwValue)
																{
																	CATIDrwDimValueComponent_var spMainValue = spDrwValue->GetFaceComponent();
																	if(!!spMainValue)
																	{
																		CATIDrwDimFormat_var spDimFormate = spMainValue->GetFormat();
																		if(!!spDimFormate)
																		{
																			spDimFormate->SetFormatUnit(CATDrwDimUnitMM);
																		}
																	}
																	CATIDrwProperties *piDrwProperties = NULL;
																	rc = piDimHoriz->QueryInterface(IID_CATIDrwProperties, (void**)&piDrwProperties);
																	if (SUCCEEDED(rc) && NULL != piDrwProperties)
																	{
																		piDrwProperties->Refresh();
																		piDrwProperties->Release();
																		piDrwProperties = NULL;
																	}
																}
															}
														}
													}
												}
												piIDMCircle2D->Release();
												piIDMCircle2D = NULL;
											}
										}
										else
										{
											IDMLine2D *piIDMLine2D = NULL;
											opSingleGenItem->QueryInterface(IID_IDMLine2D, (void**)&piIDMLine2D);
											if(NULL != piIDMLine2D)
											{
												{
													if(ddLenDia > 100)
													{
														CATIUnknownList * piSelectionsList = NULL;
														CATIUnknownListImpl * piListsel = new CATIUnknownListImpl();
														piSelectionsList = (CATIUnknownList*)piListsel;
														double dStartPoint[2];
														double dEndPoint[2];
														dStartPoint[0] = 0.0;
														dStartPoint[1] = 5.0;
														dEndPoint[0] = 50.0;
														dEndPoint[1] = 5.0;
														double  * pts[2] = { dStartPoint, dEndPoint };
														{
															piSelectionsList->Add(0, opSingleGenItem);
															CATDrwDimType dimType;
															dimType = DrwDimLength;
															CATDimDefinition dimDef;
															dimDef.Orientation = DrwDimAuto;
															CATIDrwDimDimension * piDimHoriz = NULL;
															if(bDimControl == CATFalse)
															{
																HRESULT rc = spAnnoFactory->CreateDimension(piSelectionsList, pts, dimType, &dimDef, &piDimHoriz);
																if (NULL != piDimHoriz)
																{
																	bDimControl = CATTrue;
																	if (NULL != piDimHoriz)
																	{
																		CATIDrwDimDimensionLine_var spDimLineCreated = piDimHoriz->GetDimensionLine();
																		if (!!spDimLineCreated)
																		{
																			/*CATGraphicAttributeSet attrSet;
																			attrSet.SetColorRGBA(BLUE);
																			spDimLineCreated->SetGraphicParameters(attrSet.GetColorRGBA(), 0.2);
																			double dFirstcoord[2], dSecondCoord[2], dFirstcoord1[2], dSecondCoord1[2];
																			spDimLineCreated->GetPoints(dFirstcoord1, dSecondCoord1);
																			dFirstcoord[0] = dFirstcoord1[0];
																			dFirstcoord[1] = dFirstcoord1[1] + 5;
																			dSecondCoord[0] = dSecondCoord1[0];
																			dSecondCoord[1] = dSecondCoord1[1] + 5;
																			spDimLineCreated->SetPoints(dFirstcoord, dSecondCoord);*/
																		}
																		CATISpecObject_var spCreatedDim = piDimHoriz;
																		if (!!spCreatedDim)
																		{
																			//AssignThicknessAndColor(spCreatedDim, 0, 128, 255);
																		}
																		CATIDrwDimValue_var spDrwValue = piDimHoriz->GetValue();
																		if (!!spDrwValue)
																		{
																			CATIDrwDimValueComponent_var spMainValue = spDrwValue->GetFaceComponent();
																			if(!!spMainValue)
																			{
																				CATIDrwDimFormat_var spDimFormate = spMainValue->GetFormat();
																				if(!!spDimFormate)
																				{
																					spDimFormate->SetFormatUnit(CATDrwDimUnitMM);
																				}
																			}
																			CATIDrwProperties *piDrwProperties = NULL;
																			rc = piDimHoriz->QueryInterface(IID_CATIDrwProperties, (void**)&piDrwProperties);
																			if (SUCCEEDED(rc) && NULL != piDrwProperties)
																			{
																				piDrwProperties->Refresh();
																				piDrwProperties->Release();
																				piDrwProperties = NULL;
																			}
																		}

																	}
																}
															}
														}
													}
													piIDMLine2D->Release();
													piIDMLine2D = NULL;
												}
											}
										}
										piCurve2D->Release();
										piCurve2D = NULL;
									}
								}
								IDMLine2D *piIDMLine2D = NULL;
								opSingleGenItem->QueryInterface(IID_IDMLine2D, (void**)&piIDMLine2D);
								if(NULL != piIDMLine2D)
								{
									listOfStraightGeometry.Append(opSingleGenItem);
									piIDMLine2D->Release();
									piIDMLine2D = NULL;
								}
							}
							/*if(NULL != opListOfCenterLines)
							{
								unsigned int onCenterLineCount = 0;
								opListOfCenterLines->Count(&onCenterLineCount);
								for(int nCircleCntItr = 0; nCircleCntItr < (onCenterLineCount - 1); nCircleCntItr++)
								{
									CATIUnknownList * piSelectionsList = NULL;
									CATIUnknownListImpl * piListsel = new CATIUnknownListImpl();
									piSelectionsList = (CATIUnknownList*)piListsel;
									double dStartPoint[2];
									double dEndPoint[2];
									dStartPoint[0] = 0.0;
									dStartPoint[1] = 5.0;
									dEndPoint[0] = 50.0;
									dEndPoint[1] = 5.0;
									double  * pts[2] = { dStartPoint, dEndPoint };
									{
										
										IUnknown *op1 = NULL;
										IUnknown *op2 = NULL;
										opListOfCenterLines->Item(nCircleCntItr, &op1);
										opListOfCenterLines->Item(nCircleCntItr + 1, &op2);
										if(NULL != op1 && NULL != op2)
										{
											piSelectionsList->Add(0, op1);
											piSelectionsList->Add(1, op2);
											CATDrwDimType dimType;
											dimType = DrwDimDistance;
											CATDimDefinition dimDef;
											dimDef.Orientation = DrwDimAuto;
											CATIDrwDimDimension * piDimHoriz = NULL;
											HRESULT rc = spAnnoFactory->CreateDimension(piSelectionsList, pts, dimType, &dimDef, &piDimHoriz);
											if (NULL != piDimHoriz)
											{
											}
											op1->Release();
											op1 = NULL;
											op2->Release();
											op2 = NULL;
										}
									}
								}
							}*/
							for(int nCircleItr = 1 ; nCircleItr < lsitOfCurveGeometry.Size(); ++nCircleItr)
							{
								IDMCircle2D *piIDMCircle2DFirst = NULL;
								lsitOfCurveGeometry[nCircleItr]->QueryInterface(IID_IDMCircle2D, (void**)&piIDMCircle2DFirst);
								IDMCircle2D *piIDMCircle2DSecond = NULL;
								lsitOfCurveGeometry[nCircleItr + 1]->QueryInterface(IID_IDMCircle2D, (void**)&piIDMCircle2DSecond);
								if(NULL != piIDMCircle2DFirst && NULL != piIDMCircle2DSecond)
								{
									double dCenterFirst[2], dCenterSecond[2];
									double odRadiusFirst, odRadiusSecond;
									piIDMCircle2DFirst->GetCircleData(dCenterFirst, &odRadiusFirst);
									piIDMCircle2DSecond->GetCircleData(dCenterSecond, &odRadiusSecond);
									CATISpecObject_var spCreatedPoint1Vertics = sp2DWFFactory->CreatePoint(dCenterFirst);
									CATISpecObject_var spCreatedPoint2Vertics = sp2DWFFactory->CreatePoint(dCenterSecond);
									if (!!spCreatedPoint1Vertics && !!spCreatedPoint2Vertics)
									{
										IUnknown *pPt1Un = NULL;
										IUnknown *pPt2Un = NULL;
										spCreatedPoint1Vertics->QueryInterface(IID_IUnknown, (void**)&pPt1Un);
										spCreatedPoint2Vertics->QueryInterface(IID_IUnknown, (void**)&pPt2Un);
										if (NULL != pPt1Un && NULL != pPt2Un)
										{
											CATIUnknownList * piSelectionsListVerti = NULL;
											CATIUnknownListImpl * piListselVerti = new CATIUnknownListImpl();
											piSelectionsListVerti = (CATIUnknownList*)piListselVerti;
											if (NULL != piSelectionsListVerti)
											{
												piSelectionsListVerti->Add(0, pPt2Un);
												piSelectionsListVerti->Add(1, pPt1Un);
												double  * ptsVertix[2] = { dCenterFirst, dCenterSecond };
												{
													CATDrwDimType dimTypeVertics;
													dimTypeVertics = DrwDimDistance;
													CATDimDefinition dimDefVertics;
													dimDefVertics.Orientation = DrwDimAuto;
													CATIDrwDimDimension * piDimVerticals = NULL;
													HRESULT rc = spAnnoFactory->CreateDimension(piSelectionsListVerti, ptsVertix, dimTypeVertics, &dimDefVertics, &piDimVerticals);
													if (NULL != piDimVerticals)
													{
														CATIDrwDimValue_var spDrwValue = piDimVerticals->GetValue();
														if (!!spDrwValue)
														{
															CATIDrwDimValueComponent_var spMainValue = spDrwValue->GetFaceComponent();
															if(!!spMainValue)
															{
																CATIDrwDimFormat_var spDimFormate = spMainValue->GetFormat();
																if(!!spDimFormate)
																{
																	spDimFormate->SetFormatUnit(CATDrwDimUnitMM);
																}
															}
															CATIDrwProperties *piDrwProperties = NULL;
															rc = piDimVerticals->QueryInterface(IID_CATIDrwProperties, (void**)&piDrwProperties);
															if (SUCCEEDED(rc) && NULL != piDrwProperties)
															{
																piDrwProperties->Refresh();
																piDrwProperties->Release();
																piDrwProperties = NULL;
															}
														}
													}
												}
											}
										}
									}
									piIDMCircle2DFirst->Release();
									piIDMCircle2DFirst = NULL;
									piIDMCircle2DSecond->Release();
									piIDMCircle2DSecond = NULL;
								}
							}
							//	/*CATIUnknownList * piSelectionsList = NULL;
							//	CATIUnknownListImpl * piListsel = new CATIUnknownListImpl();
							//	piSelectionsList = (CATIUnknownList*)piListsel;
							//	double dStartPoint[2];
							//	double dEndPoint[2];
							//	dStartPoint[0] = 0.0;
							//	dStartPoint[1] = 5.0;
							//	dEndPoint[0] = 50.0;
							//	dEndPoint[1] = 5.0;
							//	double  * pts[2] = { dStartPoint, dEndPoint };
							//	{
							//	piSelectionsList->Add(0, lsitOfCurveGeometry[nCircleItr]);
							//	piSelectionsList->Add(1, lsitOfCurveGeometry[nCircleItr + 1]);
							//	CATDrwDimType dimType;
							//	dimType = DrwDimDistance;
							//	CATDimDefinition dimDef;
							//	dimDef.Orientation = DrwDimAuto;
							//	CATIDrwDimDimension * piDimHoriz = NULL;
							//	HRESULT rc = spAnnoFactory->CreateDimension(piSelectionsList, pts, dimType, &dimDef, &piDimHoriz);
							//	if (NULL != piDimHoriz)
							//	{
							//	}
							//	}*/
							//}
							/*for(int nLineGeomItr = 1; nLineGeomItr <= listOfStraightGeometry.Size(); ++nLineGeomItr)
							{
								IDMLine2D *piIDMLine2D = NULL;
								listOfStraightGeometry[nLineGeomItr]->QueryInterface(IID_IDMLine2D, (void**)&piIDMLine2D);
								if(NULL != piIDMLine2D)
								{
									double dRootPoint[2], dDirection[2];
									piIDMLine2D->GetLineData(dRootPoint, dDirection);
									piIDMLine2D->Release();
									piIDMLine2D = NULL;
									CATMathVector2D mathVector2D(dDirection);
									for(int nSecondItr = nLineGeomItr + 1; nSecondItr <= listOfStraightGeometry.Size(); ++nSecondItr)
									{
										IDMLine2D *piIDMLine2DSecond = NULL;
										listOfStraightGeometry[nSecondItr]->QueryInterface(IID_IDMLine2D, (void**)&piIDMLine2DSecond);
										if(NULL != piIDMLine2DSecond)
										{
											double dRootPointSecond[2], dDirectionSecond[2];
											piIDMLine2DSecond->GetLineData(dRootPointSecond, dDirectionSecond);
											piIDMLine2DSecond->Release();
											piIDMLine2DSecond = NULL;
											CATMathVector2D mathVector2DSecond(dDirectionSecond);
											if(TRUE == mathVector2D.IsParallel(mathVector2DSecond))
											{
												CATIUnknownList * piSelectionsList = NULL;
												CATIUnknownListImpl * piListsel = new CATIUnknownListImpl();
												piSelectionsList = (CATIUnknownList*)piListsel;
												double dStartPoint[2];
												double dEndPoint[2];
												dStartPoint[0] = 0.0;
												dStartPoint[1] = 5.0;
												dEndPoint[0] = 50.0;
												dEndPoint[1] = 5.0;
												double  * pts[2] = { dStartPoint, dEndPoint };
												{
													piSelectionsList->Add(0, listOfStraightGeometry[nLineGeomItr]);
													piSelectionsList->Add(1, listOfStraightGeometry[nSecondItr]);
													CATDrwDimType dimType;
													dimType = DrwDimDistance;
													CATDimDefinition dimDef;
													dimDef.Orientation = DrwDimAuto;
													CATIDrwDimDimension * piDimHoriz = NULL;
													HRESULT rc = spAnnoFactory->CreateDimension(piSelectionsList, pts, dimType, &dimDef, &piDimHoriz);
													if (NULL != piDimHoriz)
													{
													}
												}
											}
										}
									}
								}
							}*/
						}
					}
					piGenView->Release();
					piGenView = NULL;
				}
			}
		}
	}
	CATCatch(CATError, pError)
	{
	}
	CATEndTry;
}
void TPAAutoDrawingCmd::AssignThicknessAndColor(CATISpecObject_var &ispFeature, int nRed, int nGreen, int nBlue)
{
	CATTry
	{
		CATIVisProperties_var spVisu = ispFeature;
		if (!spVisu)
			return;
		CATVisPropertiesValues oPropertyValues;
		CATVisPropertyType PropTypeOnPoint = CATVPAllPropertyType;
		CATVisGeomType GeomTypeOnPoint = CATVPLine;
		HRESULT rc = spVisu->GetPropertiesAtt(oPropertyValues, PropTypeOnPoint, GeomTypeOnPoint);
		if (FAILED(rc))
			return;
		oPropertyValues.SetColor(nRed, nGreen, nBlue);
		rc = spVisu->SetPropertiesAtt(oPropertyValues, PropTypeOnPoint, GeomTypeOnPoint);
		CATIModelEvents_var MyFeatureModelEvents = spVisu;
		if (NULL_var != MyFeatureModelEvents)
		{
			CATModifyVisProperties ModifyNotification(spVisu, NULL, GeomTypeOnPoint, PropTypeOnPoint, oPropertyValues);
			MyFeatureModelEvents->Dispatch(ModifyNotification);
		}
	}
		CATCatch(CATError, pError)
	{
	}
	CATEndTry;
}
//-------------------------------------------------------------------------
// TPAAutoDrawingCmd::OpenOKCB()
//-------------------------------------------------------------------------
void TPAAutoDrawingCmd::OpenOKCB(CATCommand          *iPublishingCommand, 
                          CATNotification     *iNotification, 
                          CATCommandClientData iUsefulData)
{
  // Retrieves the selected file name
  CATUnicodeString fileName;
  _pDlgFile->GetSelection(fileName);
   ReadJSONAndCreatePart(fileName);
   _pDlgFile->RequestDelayedDestruction();
   _pDlgFile = NULL;
   this->RequestDelayedDestruction();
}

//-------------------------------------------------------------------------
// TPAAutoDrawingCmd::OpenCANCELCB
//-------------------------------------------------------------------------
void TPAAutoDrawingCmd::OpenCANCELCB(CATCommand          *iPublishingCommand, 
                          CATNotification     *iNotification, 
                          CATCommandClientData iUsefulData)
{
   _pDlgFile->RequestDelayedDestruction();
   _pDlgFile = NULL;
   this->RequestDelayedDestruction();
}
//-------------------------------------------------------------------------
// TPAAutoDrawingCmd::ReadJSONAndCreatePart()
//-------------------------------------------------------------------------
void TPAAutoDrawingCmd::ReadJSONAndCreatePart(CATUnicodeString iusFileName)
{
	CATTry
	{
		ifstream file(iusFileName.ConvertToChar(), ios::binary);
		if (!file.is_open())
		{
			cout << "Error: Cannot open NXPartsData.json" << endl;
			return;
		}

		// Read file into Json::Value
		Json::Value root;
		Json::Reader reader;

		if (!reader.parse(file, root, false))
		{
			cout << "Error parsing JSON: " << reader.getFormattedErrorMessages() << endl;
			return;
		}
		file.close();

		int nSize = root.size();
		CATISpecObject_var spCreatedSketchBackUp;
		for (unsigned int i = 0; i < root.size(); ++i)
		{
			const Json::Value &feature = root[i];

			CATUnicodeString usFeatureType(feature["FeatureType"].asCString());
			if(usFeatureType.SearchSubString("SKETCH") >= 0)
			{
				if (!feature["SketchData"].isNull())
				{
					const Json::Value &sketchData = feature["SketchData"];
					const Json::Value &geomListTypes = sketchData["listOfGeomTypes"];
					CATListOfCATUnicodeString listOfGeomTypes;
					CATListOfDouble listOfRadius;
					for (unsigned int i = 0; i < geomListTypes.size(); i++)
					{
						listOfGeomTypes.Append(geomListTypes[i].asCString());
					}
					const Json::Value &geomListRadius = sketchData["listOfRadius"];
					for (unsigned int i = 0; i < geomListRadius.size(); i++)
					{
						listOfRadius.Append(geomListRadius[i].asDouble());
					}
					const Json::Value &geomListGeomData = sketchData["listOfGeomData"];
					std::vector<std::string> memberNames = geomListGeomData.getMemberNames();
					CATLISTP(CATMathPoint) listOfGeomPoints;
					for (unsigned int i = 0; i < memberNames.size(); i++) 
					{
						std::ostringstream oss;
						oss << (i + 1);
						std::string key = oss.str();
						const Json::Value coords = geomListGeomData[key];
						for (unsigned int j = 0; j < coords.size(); j++)
						{
							const Json::Value point = coords[j];
							if(point.size() == 3)
							{
								double dX = point[0].asDouble();
								double dY = point[1].asDouble();
								double dZ = point[2].asDouble();
								listOfGeomPoints.Append(new CATMathPoint(point[0].asDouble(), point[1].asDouble(), point[2].asDouble()));
							}
						}
					}
					if(listOfGeomTypes.Size() == listOfRadius.Size() && listOfGeomPoints.Size() >= (2 * listOfGeomTypes.Size()))
					{
						CATISketchFactory_var spSketchFactory = TPACommonUtilityClass::GetClassObject()->GetPartContainer();
						if(!!spSketchFactory)
						{
							CATIPrtPart_var spPrtPart = TPACommonUtilityClass::GetClassObject()->GetRootElement();
							if(!!spPrtPart)
							{
								CATListValCATISpecObject_var spListRefPlanes = spPrtPart->GetReferencePlanes();
								if(spListRefPlanes.Size() > 0)
								{
									CATISketch_var spSketch = spSketchFactory->CreateSketch(spListRefPlanes[1]);
									if(!!spSketch)
									{
										CATI2DWFFactory_var spWF2DFactOnSketch(spSketch);
										if(!!spWF2DFactOnSketch)
										{
											spSketch->OpenEdition();
											CATListOfInt nListOfArcIndex;
											int nArcIndex = 0;
											CATLISTV(CATISpecObject_var) listOfCreatedLines;
											CATLISTP(CATMathPoint) listOfArcPts;
											CATListOfDouble listOfRadiusForArc;
											for(int nGeomItr = 1; nGeomItr <= listOfGeomTypes.Size(); ++nGeomItr)
											{
												CATUnicodeString usGeomType = listOfGeomTypes[nGeomItr];
												if(usGeomType.SearchSubString("Line") >= 0)
												{
													int nPtsIndex = nGeomItr * 2 + nArcIndex;
													if(nPtsIndex <= listOfGeomPoints.Size())
													{
														double nStartPt[3], nEndPt[3];
														double nStartPt1[2], nEndPt1[2];
														listOfGeomPoints[nPtsIndex - 1]->GetCoord(nStartPt);
														nStartPt1[0] = nStartPt[0];
														nStartPt1[1] = nStartPt[1];
														listOfGeomPoints[nPtsIndex]->GetCoord(nEndPt);
														nEndPt1[0] = nEndPt[0];
														nEndPt1[1] = nEndPt[1];
														CATISpecObject_var spCreatedLine = spWF2DFactOnSketch->CreateLine(nStartPt1, nEndPt1);
														if(!!spCreatedLine)
														{
															listOfCreatedLines.Append(spCreatedLine);
														}
													}
												}
												else if(usGeomType.SearchSubString("Arc") >= 0)
												{
													nListOfArcIndex.Append(nGeomItr);
													nArcIndex++;
													int nPtsIndex = nGeomItr * 2 + 1;
													listOfArcPts.Append(listOfGeomPoints[nPtsIndex - 2]);
													listOfArcPts.Append(listOfGeomPoints[nPtsIndex - 1]);
													listOfArcPts.Append(listOfGeomPoints[nPtsIndex]);
													listOfRadiusForArc.Append(listOfRadius[nGeomItr]);
												}
											}
											if(listOfArcPts.Size()/3 == nArcIndex)
											{
												for(int nArcItr = 1; nArcItr <= nArcIndex; nArcItr++)
												{
													int nArcListIndex = 0;
													if(nArcItr == 1)
														nArcListIndex = nArcItr;
													else if(nArcItr == 2)
														nArcListIndex = nArcItr * 2;
													else if(nArcItr > 2)
														nArcListIndex = nArcItr * 2 + 1;
													CATMathPoint2D mpArcStartPt(listOfArcPts[nArcListIndex]->GetX(), listOfArcPts[nArcListIndex]->GetY()), mpArcEndPt(listOfArcPts[nArcListIndex+1]->GetX(), listOfArcPts[nArcListIndex+1]->GetY());
													CATLISTV(CATISpecObject_var) listOfLinesForArcCreation;
													for(int nLineItr = 1; nLineItr <= listOfCreatedLines.Size(); ++nLineItr)
													{
														CATI2DCurve *piLine = NULL;
														listOfCreatedLines[nLineItr]->QueryInterface(IID_CATI2DCurve, (void**)&piLine);
														if(NULL != piLine)
														{
															CATI2DPoint_var spStartPt = piLine->GetStartPoint();
															CATI2DPoint_var spEndPt = piLine->GetEndPoint();
															if(!!spStartPt && !!spEndPt)
															{
																double dStartPtArray[2], dEndPtArray[2];
																spStartPt->GetPointData(dStartPtArray);
																spEndPt->GetPointData(dEndPtArray);
																CATMathPoint2D mpStartPtLine(dStartPtArray[0], dStartPtArray[1]), mpEndPtLine(dEndPtArray[0], dEndPtArray[1]);
																double dDist1 = TPACommonUtilityClass::GetClassObject()->RoundToSingleDecimal(mpArcStartPt.DistanceTo(mpStartPtLine));
																double dDist2 = TPACommonUtilityClass::GetClassObject()->RoundToSingleDecimal(mpArcStartPt.DistanceTo(mpEndPtLine));
																double dDist3 = TPACommonUtilityClass::GetClassObject()->RoundToSingleDecimal(mpArcEndPt.DistanceTo(mpStartPtLine));
																double dDist4 = TPACommonUtilityClass::GetClassObject()->RoundToSingleDecimal(mpArcEndPt.DistanceTo(mpEndPtLine));
																if(dDist1 == 0.0 || dDist2 == 0.0 || dDist3 == 0.0 || dDist4 == 0.0)
																{
																	listOfLinesForArcCreation.Append(listOfCreatedLines[nLineItr]);
																}
															}
															piLine->Release();
															piLine = NULL;
														}
													}
													if(listOfLinesForArcCreation.Size() == 2)
													{
														CATI2DCurve *piFirstLine = NULL;
														CATI2DCurve *piSecondLine = NULL;
														listOfLinesForArcCreation[1]->QueryInterface(IID_CATI2DCurve, (void**)&piFirstLine);
														listOfLinesForArcCreation[2]->QueryInterface(IID_CATI2DCurve, (void**)&piSecondLine);
														if(NULL != piFirstLine && NULL != piSecondLine)
														{
															double dCenterPt[3];
															double dCenterPt1[2];
															listOfArcPts[nArcListIndex+2]->GetCoord(dCenterPt);
															dCenterPt1[0] = dCenterPt[0];
															dCenterPt1[1] = dCenterPt[1];
															const double dCornerRadius = listOfRadiusForArc[nArcItr];
															spWF2DFactOnSketch->CreateCorner(piFirstLine, piSecondLine, dCenterPt1, &dCornerRadius);
															piFirstLine->Release();
															piFirstLine = NULL;
															piSecondLine->Release();
															piSecondLine = NULL;
														}
													}
												}
											}
											/*if(listOfArcPts.Size() == nListOfArcIndex.Size())
											{
												for(int nArcItr = 1; nArcItr <= nListOfArcIndex.Size(); ++nArcItr)
												{
													int nArcIndex = nListOfArcIndex[nArcItr];
													if(listOfCreatedLines.Size() >= nArcIndex)
													{
														CATI2DCurve *piFirstLine = NULL;
														CATI2DCurve *piSecondLine = NULL;
														listOfCreatedLines[nArcIndex - 1]->QueryInterface(IID_CATI2DCurve, (void**)&piFirstLine);
														listOfCreatedLines[nArcIndex]->QueryInterface(IID_CATI2DCurve, (void**)&piSecondLine);
														if(NULL != piFirstLine && NULL != piSecondLine)
														{
															double dCenterPt[3];
															double dCenterPt1[2];
															listOfArcPts[nArcItr]->GetCoord(dCenterPt);
															dCenterPt1[0] = dCenterPt[0];
															dCenterPt1[1] = dCenterPt[1];
															const double dCornerRadius = listOfRadius[nArcIndex];
															spWF2DFactOnSketch->CreateCorner(piFirstLine, piSecondLine, dCenterPt1, &dCornerRadius);
															piFirstLine->Release();
															piFirstLine = NULL;
															piSecondLine->Release();
															piSecondLine = NULL;
														}
													}
													else if(listOfCreatedLines.Size() >= (nArcIndex - 1))
													{
														CATI2DCurve *piFirstLine = NULL;
														CATI2DCurve *piSecondLine = NULL;
														listOfCreatedLines[nArcIndex - 1]->QueryInterface(IID_CATI2DCurve, (void**)&piFirstLine);
														listOfCreatedLines[1]->QueryInterface(IID_CATI2DCurve, (void**)&piSecondLine);
														if(NULL != piFirstLine && NULL != piSecondLine)
														{
															double dCenterPt[3];
															double dCenterPt1[2];
															listOfArcPts[nArcItr]->GetCoord(dCenterPt);
															dCenterPt1[0] = dCenterPt[0];
															dCenterPt1[1] = dCenterPt[1];
															const double dCornerRadius = listOfRadius[nArcIndex];
															spWF2DFactOnSketch->CreateCorner(piFirstLine, piSecondLine, dCenterPt1, &dCornerRadius);
															piFirstLine->Release();
															piFirstLine = NULL;
															piSecondLine->Release();
															piSecondLine = NULL;
														}
													}
												}
											}*/
											spSketch->CloseEdition();
											TPACommonUtilityClass::GetClassObject()->GetRootElement()->Update();
											spCreatedSketchBackUp = spSketch;
										}
									}
								}
							}
						}
					}
				}
			}

			// SketchData

			// RevolveData
			if (!feature["RevolveData"].isNull())
			{
				if(!!spCreatedSketchBackUp)
				{
					const Json::Value &rev = feature["RevolveData"];
					double dStartAngle = rev["StartAngle"].asDouble();
					double dEndAngle = rev["EndAngle"].asDouble();
					const Json::Value &Vector1 = rev["Vector"];
					for (unsigned int j = 0; j < Vector1.size(); j++)
					{
						const Json::Value Vector = Vector1[j];
						if(Vector.size() == 3)
						{
							if(Vector.size() == 3)
							{
								double dX = Vector[0].asDouble();
								double dY = Vector[1].asDouble();
								double dZ = Vector[2].asDouble();
								CATICkeParmFactory_var spParamFactory = TPACommonUtilityClass::GetClassObject()->GetPartContainer();
								if(!!spParamFactory)
								{
									CATICkeParm_var spCreatedParameterX = spParamFactory->CreateLength ("X",dX);
									CATICkeParm_var spCreatedParameterY = spParamFactory->CreateLength ("Y",dY);
									CATICkeParm_var spCreatedParameterZ = spParamFactory->CreateLength ("Z",dZ);
									CATICkeParm_var spCreatedParameterEndAngle = spParamFactory->CreateLength ("End", dEndAngle);
									if(!!spCreatedParameterX && !!spCreatedParameterY && !!spCreatedParameterZ && !!spCreatedParameterEndAngle)
									{
										CATIGSMFactory_var spGSMFactory = TPACommonUtilityClass::GetClassObject()->GetPartContainer();
										if(!!spGSMFactory)
										{
											CATISpecObject_var spCreatedDirection = spGSMFactory->CreateDirection(spCreatedParameterX, spCreatedParameterY, spCreatedParameterZ);
											if(!!spCreatedDirection)
											{
												CATIPrtFactory_var spPrtFactory = TPACommonUtilityClass::GetClassObject()->GetPartContainer();
												if(!!spPrtFactory)
												{
													CATISpecObject_var spCreatedShaft = spPrtFactory->CreateShaft(spCreatedSketchBackUp);
													if(!!spCreatedShaft)
													{
														CATIShaft_var spShaft = spCreatedShaft;
														if(!!spShaft)
														{
															spShaft->ModifyAxis(spCreatedDirection);
															spShaft->ModifyStartAngle(dStartAngle);
															spShaft->ModifyEndAngle(dEndAngle);
															spCreatedShaft->Update();
															CATIPrtProceduralView_var spPrtProceduralView = spCreatedShaft;
															if(!!spPrtProceduralView)
															{
																CATIPartRequest_var spPrtRequest = TPACommonUtilityClass::GetClassObject()->GetRootElement();
																CATIPrtPart_var spPrtPart = TPACommonUtilityClass::GetClassObject()->GetRootElement();
																if(!!spPrtRequest && !!spPrtPart)
																{
																	CATBaseUnknown_var spMainBody;
																	spPrtRequest->GetMainBody("MfDefault3DView", spMainBody);
																	if(!!spMainBody)
																	{
																		spPrtPart->SetCurrentFeature(spMainBody);
																		CATTry
																		{
																			spPrtProceduralView->InsertInProceduralView();
																			CATBody_var spCreatedShaftBody = TPACommonUtilityClass::GetClassObject()->GetBodyFromFeature(spCreatedShaft);
																			if(!!spCreatedShaftBody)
																			{
																				CATLISTP(CATCell) listOfShaftEdges;
																				spCreatedShaftBody->GetAllCells(listOfShaftEdges, 1);
																				for(int nEdgeItr = 1; nEdgeItr <= listOfShaftEdges.Size(); ++nEdgeItr)
																				{
																					CATLISTP(CATMathPoint) listOfTessPts = TPACommonUtilityClass::GetClassObject()->CellTessellation((CATEdge*)listOfShaftEdges[nEdgeItr]);
																					if(listOfTessPts.Size() > 2)
																					{
																						CATISpecObject_var ospEdgeFeaturize;
																						TPACommonUtilityClass::GetClassObject()->FeaturizeTopologicalObject(listOfShaftEdges[nEdgeItr], spCreatedShaftBody, ospEdgeFeaturize);
																						if(!!ospEdgeFeaturize)
																						{
																							CATLISTV(CATISpecObject_var) listOfFeaturesToChamfer;
																							listOfFeaturesToChamfer.Append(ospEdgeFeaturize);
																							CATISpecObject_var spCreatedChamfer = spPrtFactory->CreateChamfer(&listOfFeaturesToChamfer, _TANGENCY, LENGTH, 10, 5);
																							if(!!spCreatedChamfer)
																							{
																								TPACommonUtilityClass::GetClassObject()->InsertFeature(spCreatedChamfer);
																							}

																						}
																					}
																				}
																			}
																			CATTry
																			{
																				TPACommonUtilityClass::GetClassObject()->GetRootElement()->Update();
																			}
																			CATCatch(CATError, pError)
																			{
																			}
																			CATEndTry;
																		}
																		CATCatch(CATError, pError)
																		{
																			CATTry
																			{
																				TPACommonUtilityClass::GetClassObject()->GetRootElement()->Update();
																				CATBody_var spCreatedShaftBody = TPACommonUtilityClass::GetClassObject()->GetBodyFromFeature(spCreatedShaft);
																				if(!!spCreatedShaftBody)
																				{
																					CATLISTP(CATCell) listOfShaftEdges;
																					spCreatedShaftBody->GetAllCells(listOfShaftEdges, 1);
																					CATCell *pLongestEdge = NULL;
																					double dBackUpLength = 0.0;
																					for(int nEdgeItr = 1; nEdgeItr <= listOfShaftEdges.Size(); ++nEdgeItr)
																					{
																						CATEdge *pEdge = (CATEdge*)listOfShaftEdges[nEdgeItr];
																						if(NULL == pEdge)
																							continue;
																						double dLength = pEdge->CalcLength();
																						if(dLength > dBackUpLength)
																						{
																							dBackUpLength = dLength;
																							pLongestEdge = listOfShaftEdges[nEdgeItr];
																						}
																					}
																					if(NULL != pLongestEdge)
																					{
																						CATLISTP(CATMathPoint) listOfTessPts = TPACommonUtilityClass::GetClassObject()->CellTessellation((CATEdge*)pLongestEdge);
																						if(listOfTessPts.Size() > 2)
																						{
																							CATISpecObject_var ospEdgeFeaturize;
																							TPACommonUtilityClass::GetClassObject()->FeaturizeTopologicalObject(pLongestEdge, spCreatedShaftBody, ospEdgeFeaturize);
																							if(!!ospEdgeFeaturize)
																							{
																								CATLISTV(CATISpecObject_var) listOfFeaturesToChamfer;
																								listOfFeaturesToChamfer.Append(ospEdgeFeaturize);
																								CATISpecObject_var spCreatedChamfer = spPrtFactory->CreateChamfer(&listOfFeaturesToChamfer, _TANGENCY, LENGTH, 30, 10);
																								if(!!spCreatedChamfer)
																								{
																									TPACommonUtilityClass::GetClassObject()->InsertFeature(spCreatedChamfer);
																								}

																							}
																						}
																					}
																					TPACommonUtilityClass::GetClassObject()->GetRootElement()->Update();
																					CATLISTP(CATCell) listOfShaftFaces;
																					spCreatedShaftBody->GetAllCells(listOfShaftFaces, 2);
																					CATBoolean bRanGoto = CATFalse;
RepeatLoop:
																					CATCell *pBiggestFace = NULL;
																					double dBackUpArea = 0.0;
																					for(int nFaceItr = 1; nFaceItr <= listOfShaftFaces.Size(); ++nFaceItr)
																					{
																						CATFace *pFace = (CATFace*)listOfShaftFaces[nFaceItr];
																						if(NULL == pFace)
																							continue;
																						double dArea = pFace->CalcArea();
																						if(dArea > dBackUpArea)
																						{
																							dBackUpArea = dArea;
																							pBiggestFace = listOfShaftFaces[nFaceItr];
																						}
																					}
																					if(pBiggestFace != NULL && bRanGoto == CATFalse )
																					{
																						bRanGoto = CATTrue;
																						listOfShaftFaces.RemoveValue(pBiggestFace);
																						goto RepeatLoop;
																					}
																					if(NULL != pBiggestFace)
																					{
																						CATISpecObject_var ospFaceFeaturize;
																						TPACommonUtilityClass::GetClassObject()->FeaturizeTopologicalObject(pBiggestFace, spCreatedShaftBody, ospFaceFeaturize);
																						if(!!ospFaceFeaturize)
																						{
																							CATFace *pLargestFace = (CATFace*)pBiggestFace;
																							if(NULL != pLargestFace)
																							{
																								CATSurParam oCenterParam;
																								pLargestFace->EstimateCenterParam(oCenterParam);
																								CATMathVector oDirection;
																								pLargestFace->EvalNormal(oCenterParam, oDirection, TRUE);
																								CATICkeParmFactory_var spParmFactory = TPACommonUtilityClass::GetClassObject()->GetPartContainer();
																								if(!!spParmFactory)
																								{
																									CATICkeParm_var spX = spParmFactory->CreateReal("X", oDirection.GetX());
																									CATICkeParm_var spY = spParmFactory->CreateReal("Y", oDirection.GetY());
																									CATICkeParm_var spZ = spParmFactory->CreateReal("Z", oDirection.GetZ());
																									if(!!spX && !!spY && !!spZ)
																									{
																										CATIGSMFactory_var spGSMFactory = TPACommonUtilityClass::GetClassObject()->GetGSMFactory();
																										if(!!spGSMFactory)
																										{
																											CATISpecObject_var spCreateDirection = spGSMFactory->CreateDirection(spX, spY, spZ);
																											if(!!spCreatedDirection)
																											{
																												spCreatedDirection->Update();
																												CATISpecObject_var spCreatedHole = spPrtFactory->CreateHole(ospFaceFeaturize, NULL_var);
																												if(!!spCreatedHole)
																												{
																													CATINewHole_var spNewHole = spCreatedHole;
																													if(!!spNewHole)
																													{
																														spNewHole->SetDiameter(50.00);
																														spNewHole->SetHoleType(0);
																														spNewHole->SetLimit(2 , NULL_var);
																														CATMathPoint ompPosition;
																														CATMathDirection ompDirection;
																														spNewHole->GetPosition(ompPosition, ompDirection);
																														ompPosition.SetY(ompPosition.GetY() + 30);
																														spNewHole->SetOrigin(ompPosition);
																													}
																													CATTry
																													{
																														spCreatedHole->Update();
																													}
																													CATCatch(CATError, pError)
																													{
																														TPACommonUtilityClass::GetClassObject()->InsertFeature(spCreatedHole);
																													}CATEndTry;
																													TPACommonUtilityClass::GetClassObject()->InsertFeature(spCreatedHole);
																													TPACommonUtilityClass::GetClassObject()->GetRootElement()->Update();
																												}
																											}
																										}
																									}
																								}
																							}
																						}
																					}
																				}
																			}
																			CATCatch(CATError, pError)
																			{
																			}
																			CATEndTry;
																		}
																		CATEndTry;
																	}
																}
															}
														}
													}
													/*CATISpecObject_var spCreatedRotate = spPrtFactory->CreateRotate(spCreatedSketchBackUp, spCreatedDirection, spCreatedParameterEndAngle);
													if(!!spCreatedRotate)
													{
													CATIPrtProceduralView_var spPrtProceduralView = spCreatedRotate;
													if(!!spPrtProceduralView)
													{
													spPrtProceduralView->InsertInProceduralView();
													TPACommonUtilityClass::GetClassObject()->GetRootElement()->Update();
													}
													}*/
												}
											}
										}
									}
								}
							}
						}
					}

				}
			}
		}
		CreateDrawingAndViews();
		cout << "--------------------------------------" << endl;
		cout << "JSON file read successfully!" << endl;
	}
	CATCatch(CATError, pError)
	{
	}
	CATEndTry;
}
