# COPYRIGHT Dassault Systemes 2026
#======================================================================
# Imakefile for module TPACommonAdding.m
#======================================================================
#
#  Feb 2026  Creation: Code generated by the CAA wizard  Praveen
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP PartItf PartInterfacesUUID 
# END WIZARD EDITION ZONE

LINK_WITH = CATApplicationFrame  \
			CATGSMUseItf \
			CATMechanicalModelerUI \
			CATPartInterfaces \
			$(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
