// COPYRIGHT Dassault Systemes 2024
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TPACommonFW
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  May 2024  Creation: Code generated by the CAA wizard  Prasad
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("PartInterfaces",Protected);
AddPrereqComponent("CATGSMUseItf",Protected);
AddPrereqComponent("VisualizationBase",Protected);
AddPrereqComponent("ObjectSpecsModeler",Protected);
AddPrereqComponent("MecModInterfaces",Protected);
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("GSMInterfaces",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("GMModelInterfaces",Protected);
AddPrereqComponent("InteractiveInterfaces",Protected);
AddPrereqComponent("Tessellation",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("GeometricObjects",Protected);
AddPrereqComponent("GeometricOperators",Protected);
AddPrereqComponent("TopologicalOperatorsLight",Protected);
AddPrereqComponent("Visualization",Protected);
AddPrereqComponent("MechanicalModeler",Protected);
AddPrereqComponent("MechanicalCommands",Protected);