// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// TPADVSDirectView3DDlg.cpp
// The dialog : TPADVSDirectView3DDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  May 2026  Creation: Code generated by the CAA wizard  Praveen
//===================================================================
#include "TPADVSDirectView3DDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef TPADVSDirectView3DDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
TPADVSDirectView3DDlg::TPADVSDirectView3DDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"TPADVSDirectView3DDlg",CATDlgWndBtnOKApplyClose|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _FrmDefinition = NULL;
 _FrmDefinitionInputs = NULL;
 _LblBaseData = NULL;
 _LblStandard = NULL;
 _LblLoading = NULL;
 _SelListBaseData = NULL;
 _SelListStandard = NULL;
 _SelListLoading = NULL;
 _CheckButtFree = NULL;
 _FrmDefinitionUse = NULL;
 _RadioButtUseStandardEyes = NULL;
 _RadioButtUseV5Pts = NULL;
 _RadioButtUseMultipleEyes = NULL;
 _Frame007 = NULL;
 _TabContainer008 = NULL;
 _FirstPage = NULL;
 _FrmView = NULL;
 _Frame019 = NULL;
 _LblRange = NULL;
 _SpinnerRange = NULL;
 _LablComputation = NULL;
 _Combo022 = NULL;
 _Frame020 = NULL;
 _LblOrientation = NULL;
 _ComboOrientation = NULL;
 _SpinnerOrientationDegree = NULL;
 _FrmTargetSurface = NULL;
 _Frame029 = NULL;
 _LblTypeTargetSurface = NULL;
 _Combo028 = NULL;
 _EditorTargetSurfaceTypeValue = NULL;
 _Frame030 = NULL;
 _CheckButtVisualizeTargetSurface = NULL;
 _FrmSelSurface = NULL;
 _Frame033 = NULL;
 _LblSurface = NULL;
 _EditorSurface = NULL;
 _PushButtCGR = NULL;
 _Frame037 = NULL;
 _CheckButtVisuaSelSurface = NULL;
 _FrmDiscretization = NULL;
 _LblDiscretization = NULL;
 _LblAccurate = NULL;
 _FrmUserSelInput = NULL;
 _TabContainer039 = NULL;
 _TabVehicleGeometry = NULL;
 _MulitListVehicleGeometry = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _SliderAccuracy = NULL;
  _FrmVolumetric = NULL;
  _LblComplianceStandard = NULL;
  _ComboStandard = NULL;
  _LblGroundPlane = NULL;
  _EditorGroundPlane = NULL;
  _RadioButtGenFromAHP = NULL;
  _RadioButtSelectDirectly = NULL;
  _LblAccelKeyPt = NULL;
  _EditorAccelKeyPt = NULL;
  _LblSeatMidPt = NULL;
  _EditorSeatMidPt = NULL;
  _LblLengthOffset = NULL;
  _SpinnerLengthOffset = NULL;
  _LblLeftEye = NULL;
  _EditorLeftEye = NULL;
  _LblMidEye = NULL;
  _EditorMidEye = NULL;
  _LblRightEye = NULL;
  _EditorRightEye = NULL;
  _LblNeckPivot = NULL;
  _SpinnerNeckPivot = NULL;
  _LblHeadRotation = NULL;
  _SpinnerHeadRotation = NULL;
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
TPADVSDirectView3DDlg::~TPADVSDirectView3DDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _FrmDefinition = NULL;
 _FrmDefinitionInputs = NULL;
 _LblBaseData = NULL;
 _LblStandard = NULL;
 _LblLoading = NULL;
 _SelListBaseData = NULL;
 _SelListStandard = NULL;
 _SelListLoading = NULL;
 _CheckButtFree = NULL;
 _FrmDefinitionUse = NULL;
 _RadioButtUseStandardEyes = NULL;
 _RadioButtUseV5Pts = NULL;
 _RadioButtUseMultipleEyes = NULL;
 _Frame007 = NULL;
 _TabContainer008 = NULL;
 _FirstPage = NULL;
 _FrmView = NULL;
 _Frame019 = NULL;
 _LblRange = NULL;
 _SpinnerRange = NULL;
 _LablComputation = NULL;
 _Combo022 = NULL;
 _Frame020 = NULL;
 _LblOrientation = NULL;
 _ComboOrientation = NULL;
 _SpinnerOrientationDegree = NULL;
 _FrmTargetSurface = NULL;
 _Frame029 = NULL;
 _LblTypeTargetSurface = NULL;
 _Combo028 = NULL;
 _EditorTargetSurfaceTypeValue = NULL;
 _Frame030 = NULL;
 _CheckButtVisualizeTargetSurface = NULL;
 _FrmSelSurface = NULL;
 _Frame033 = NULL;
 _LblSurface = NULL;
 _EditorSurface = NULL;
 _PushButtCGR = NULL;
 _Frame037 = NULL;
 _CheckButtVisuaSelSurface = NULL;
 _FrmDiscretization = NULL;
 _LblDiscretization = NULL;
 _LblAccurate = NULL;
 _FrmUserSelInput = NULL;
 _TabContainer039 = NULL;
 _TabVehicleGeometry = NULL;
 _MulitListVehicleGeometry = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _SliderAccuracy = NULL;
  _FrmVolumetric = NULL;
  _LblComplianceStandard = NULL;
  _ComboStandard = NULL;
  _LblGroundPlane = NULL;
  _EditorGroundPlane = NULL;
  _RadioButtGenFromAHP = NULL;
  _RadioButtSelectDirectly = NULL;
  _LblAccelKeyPt = NULL;
  _EditorAccelKeyPt = NULL;
  _LblSeatMidPt = NULL;
  _EditorSeatMidPt = NULL;
  _LblLengthOffset = NULL;
  _SpinnerLengthOffset = NULL;
  _LblLeftEye = NULL;
  _EditorLeftEye = NULL;
  _LblMidEye = NULL;
  _EditorMidEye = NULL;
  _LblRightEye = NULL;
  _EditorRightEye = NULL;
  _LblNeckPivot = NULL;
  _SpinnerNeckPivot = NULL;
  _LblHeadRotation = NULL;
  _SpinnerHeadRotation = NULL;
}



void TPADVSDirectView3DDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _FrmDefinition = new CATDlgFrame(this, "FrmDefinition", CATDlgGridLayout);
_FrmDefinition -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _FrmDefinitionInputs = new CATDlgFrame(_FrmDefinition, "FrmDefinitionInputs", CATDlgFraNoFrame|CATDlgGridLayout);
_FrmDefinitionInputs -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _LblBaseData = new CATDlgLabel(_FrmDefinitionInputs, "LblBaseData");
_LblBaseData -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _LblStandard = new CATDlgLabel(_FrmDefinitionInputs, "LblStandard");
_LblStandard -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _LblLoading = new CATDlgLabel(_FrmDefinitionInputs, "LblLoading");
_LblLoading -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _SelListBaseData = new CATDlgSelectorList(_FrmDefinitionInputs, "SelListBaseData");
 _SelListBaseData -> SetVisibleTextHeight(1);
 _SelListBaseData -> SetVisibleTextWidth(16);
_SelListBaseData -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _SelListStandard = new CATDlgSelectorList(_FrmDefinitionInputs, "SelListStandard");
 _SelListStandard -> SetVisibleTextHeight(1);
 _SelListStandard -> SetVisibleTextWidth(16);
_SelListStandard -> SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
 _SelListLoading = new CATDlgSelectorList(_FrmDefinitionInputs, "SelListLoading");
 _SelListLoading -> SetVisibleTextHeight(1);
 _SelListLoading -> SetVisibleTextWidth(16);
_SelListLoading -> SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);
 _CheckButtFree = new CATDlgCheckButton(_FrmDefinitionInputs, "CheckButtFree");
_CheckButtFree -> SetGridConstraints(1, 2, 1, 1, CATGRID_4SIDES);
 _FrmDefinitionUse = new CATDlgFrame(_FrmDefinition, "FrmDefinitionUse", CATDlgFraNoFrame|CATDlgGridLayout);
_FrmDefinitionUse -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _RadioButtUseStandardEyes = new CATDlgRadioButton(_FrmDefinitionUse, "RadioButtUseStandardEyes");
_RadioButtUseStandardEyes -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _RadioButtUseV5Pts = new CATDlgRadioButton(_FrmDefinitionUse, "RadioButtUseV5Pts");
_RadioButtUseV5Pts -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _RadioButtUseMultipleEyes = new CATDlgRadioButton(_FrmDefinitionUse, "RadioButtUseMultipleEyes");
_RadioButtUseMultipleEyes -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Frame007 = new CATDlgFrame(this, "Frame007", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame007 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _TabContainer008 = new CATDlgTabContainer(_Frame007, "TabContainer008");
_TabContainer008 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _FirstPage = new CATDlgTabPage(_TabContainer008, "FirstPage", CATDlgGridLayout);
 _FrmView = new CATDlgFrame(_FirstPage, "FrmView", CATDlgGridLayout);
_FrmView -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame019 = new CATDlgFrame(_FrmView, "Frame019", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame019 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _LblRange = new CATDlgLabel(_Frame019, "LblRange");
_LblRange -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _SpinnerRange = new CATDlgSpinner(_Frame019, "SpinnerRange", CATDlgSpnEntry|CATDlgSpnDouble);
 _SpinnerRange -> SetMinMaxStep(0.000000, 360.000000, 1.000000);
 _SpinnerRange -> SetUnit (CATDlgControl::Degree);
 _SpinnerRange -> SetMagnitude (CATDlgControl::Angle);
 _SpinnerRange -> SetPrecision( 0 );
_SpinnerRange -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _LablComputation = new CATDlgLabel(_Frame019, "LablComputation");
_LablComputation -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Combo022 = new CATDlgCombo(_Frame019, "Combo022", CATDlgCmbDropDown|CATDlgCmbDouble);
 _Combo022 -> SetPrecision( 0 );
_Combo022 -> SetGridConstraints(0, 3, 1, 1, CATGRID_4SIDES);
 _Frame020 = new CATDlgFrame(_FrmView, "Frame020", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame020 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _LblOrientation = new CATDlgLabel(_Frame020, "LblOrientation");
_LblOrientation -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _ComboOrientation = new CATDlgCombo(_Frame020, "ComboOrientation", CATDlgCmbDropDown|CATDlgCmbDouble);
 _ComboOrientation -> SetPrecision( 0 );
_ComboOrientation -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _SpinnerOrientationDegree = new CATDlgSpinner(_Frame020, "SpinnerOrientationDegree", CATDlgSpnEntry);
 _SpinnerOrientationDegree -> SetRange(0.000000, 360.000000, (float)360.000000);
_SpinnerOrientationDegree -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _FrmTargetSurface = new CATDlgFrame(_FirstPage, "FrmTargetSurface", CATDlgGridLayout);
_FrmTargetSurface -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _Frame029 = new CATDlgFrame(_FrmTargetSurface, "Frame029", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame029 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _LblTypeTargetSurface = new CATDlgLabel(_Frame029, "LblTypeTargetSurface");
_LblTypeTargetSurface -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Combo028 = new CATDlgCombo(_Frame029, "Combo028", CATDlgCmbDropDown|CATDlgCmbDouble);
 _Combo028 -> SetPrecision( 0 );
_Combo028 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _EditorTargetSurfaceTypeValue = new CATDlgEditor(_Frame029, "EditorTargetSurfaceTypeValue");
_EditorTargetSurfaceTypeValue -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Frame030 = new CATDlgFrame(_FrmTargetSurface, "Frame030", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame030 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _CheckButtVisualizeTargetSurface = new CATDlgCheckButton(_Frame030, "CheckButtVisualizeTargetSurface");
_CheckButtVisualizeTargetSurface -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _FrmSelSurface = new CATDlgFrame(_FirstPage, "FrmSelSurface", CATDlgGridLayout);
_FrmSelSurface -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _Frame033 = new CATDlgFrame(_FrmSelSurface, "Frame033", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame033 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _LblSurface = new CATDlgLabel(_Frame033, "LblSurface");
_LblSurface -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _EditorSurface = new CATDlgEditor(_Frame033, "EditorSurface");
 _EditorSurface -> SetVisibleTextHeight(1);
 _EditorSurface -> SetVisibleTextWidth(25);
_EditorSurface -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _PushButtCGR = new CATDlgPushButton(_Frame033, "PushButtCGR");
_PushButtCGR -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Frame037 = new CATDlgFrame(_FrmSelSurface, "Frame037", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame037 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _CheckButtVisuaSelSurface = new CATDlgCheckButton(_Frame037, "CheckButtVisuaSelSurface");
_CheckButtVisuaSelSurface -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _FrmDiscretization = new CATDlgFrame(_FirstPage, "FrmDiscretization", CATDlgFraNoFrame|CATDlgGridLayout);
_FrmDiscretization -> SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);
 _LblDiscretization = new CATDlgLabel(_FrmDiscretization, "LblDiscretization");
_LblDiscretization -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _LblAccurate = new CATDlgLabel(_FrmDiscretization, "LblAccurate");
_LblAccurate -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _FrmUserSelInput = new CATDlgFrame(this, "FrmUserSelInput", CATDlgFraNoFrame|CATDlgGridLayout);
_FrmUserSelInput -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _TabContainer039 = new CATDlgTabContainer(_FrmUserSelInput, "TabContainer039");
_TabContainer039 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _TabVehicleGeometry = new CATDlgTabPage(_TabContainer039, "TabVehicleGeometry", CATDlgGridLayout);
 _MulitListVehicleGeometry = new CATDlgMultiList(_TabVehicleGeometry, "MulitListVehicleGeometry");
 CATUnicodeString MulitListVehicleGeometryTitles [ 2 ];
 MulitListVehicleGeometryTitles[0] = CATMsgCatalog::BuildMessage("TPADVSDirectView3DDlg", "FrmUserSelInput.TabContainer039.TabVehicleGeometry.MulitListVehicleGeometry.ColumnTitle1");
 MulitListVehicleGeometryTitles[1] = CATMsgCatalog::BuildMessage("TPADVSDirectView3DDlg", "FrmUserSelInput.TabContainer039.TabVehicleGeometry.MulitListVehicleGeometry.ColumnTitle2");
 _MulitListVehicleGeometry -> SetColumnTitles(2, MulitListVehicleGeometryTitles);
 _MulitListVehicleGeometry -> SetVisibleColumnCount( 2 );
 _MulitListVehicleGeometry->SetColumnTextWidth (0, 23);
 _MulitListVehicleGeometry->SetColumnTextWidth (1, 10);
_MulitListVehicleGeometry -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION
_SliderAccuracy = new CATDlgSlider(_FrmDiscretization, "SliderAccuracyID", CATDlgCtrHorizontal);
_SliderAccuracy->SetRange((float)0.1, 10, 100);
_SliderAccuracy->SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
_SliderAccuracy->SetCurrentValue((float)0.1, 0);
_SpinnerRange->SetValue(90, 0);
_SliderAccuracy->SetDecimalPoint(2);

// Volumetric DVS additions
_FrmVolumetric = new CATDlgFrame(this, "FrmVolumetric", CATDlgGridLayout);
_FrmVolumetric->SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);

_LblComplianceStandard = new CATDlgLabel(_FrmVolumetric, "LblComplianceStandard");
_LblComplianceStandard->SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
_ComboStandard = new CATDlgCombo(_FrmVolumetric, "ComboStandard", CATDlgCmbDropDown);
_ComboStandard->SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
_ComboStandard->SetLine("London DVS (TfL)", 0);
_ComboStandard->SetLine("UNECE R125", 1);
_ComboStandard->SetLine("UNECE R167", 2);
_ComboStandard->SetLine("ISO 5006", 3);
_ComboStandard->SetLine("Custom / Free", 4);
_ComboStandard->SelectLine(0);

_LblGroundPlane = new CATDlgLabel(_FrmVolumetric, "LblGroundPlane");
_LblGroundPlane->SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
_EditorGroundPlane = new CATDlgEditor(_FrmVolumetric, "EditorGroundPlane");
_EditorGroundPlane->SetGridConstraints(1, 1, 1, 1, CATGRID_4SIDES);
_EditorGroundPlane->SetReadOnly(TRUE);

_RadioButtGenFromAHP = new CATDlgRadioButton(_FrmVolumetric, "RadioButtGenFromAHP");
_RadioButtGenFromAHP->SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
_RadioButtGenFromAHP->SetState(CATDlgCheck, TRUE);

_RadioButtSelectDirectly = new CATDlgRadioButton(_FrmVolumetric, "RadioButtSelectDirectly");
_RadioButtSelectDirectly->SetGridConstraints(2, 1, 1, 1, CATGRID_4SIDES);

_LblAccelKeyPt = new CATDlgLabel(_FrmVolumetric, "LblAccelKeyPt");
_LblAccelKeyPt->SetGridConstraints(3, 0, 1, 1, CATGRID_4SIDES);
_EditorAccelKeyPt = new CATDlgEditor(_FrmVolumetric, "EditorAccelKeyPt");
_EditorAccelKeyPt->SetGridConstraints(3, 1, 1, 1, CATGRID_4SIDES);
_EditorAccelKeyPt->SetReadOnly(TRUE);

_LblSeatMidPt = new CATDlgLabel(_FrmVolumetric, "LblSeatMidPt");
_LblSeatMidPt->SetGridConstraints(4, 0, 1, 1, CATGRID_4SIDES);
_EditorSeatMidPt = new CATDlgEditor(_FrmVolumetric, "EditorSeatMidPt");
_EditorSeatMidPt->SetGridConstraints(4, 1, 1, 1, CATGRID_4SIDES);
_EditorSeatMidPt->SetReadOnly(TRUE);

_LblLengthOffset = new CATDlgLabel(_FrmVolumetric, "LblLengthOffset");
_LblLengthOffset->SetGridConstraints(5, 0, 1, 1, CATGRID_4SIDES);
_SpinnerLengthOffset = new CATDlgSpinner(_FrmVolumetric, "SpinnerLengthOffset", CATDlgSpnEntry|CATDlgSpnDouble);
_SpinnerLengthOffset->SetMinMaxStep(0.000000, 2000.000000, 10.000000);
_SpinnerLengthOffset->SetValue(678.0);
_SpinnerLengthOffset->SetGridConstraints(5, 1, 1, 1, CATGRID_4SIDES);

_LblLeftEye = new CATDlgLabel(_FrmVolumetric, "LblLeftEye");
_LblLeftEye->SetGridConstraints(6, 0, 1, 1, CATGRID_4SIDES);
_EditorLeftEye = new CATDlgEditor(_FrmVolumetric, "EditorLeftEye");
_EditorLeftEye->SetGridConstraints(6, 1, 1, 1, CATGRID_4SIDES);
_EditorLeftEye->SetReadOnly(TRUE);
_EditorLeftEye->SetSensitivity(CATDlgDisable);

_LblMidEye = new CATDlgLabel(_FrmVolumetric, "LblMidEye");
_LblMidEye->SetGridConstraints(7, 0, 1, 1, CATGRID_4SIDES);
_EditorMidEye = new CATDlgEditor(_FrmVolumetric, "EditorMidEye");
_EditorMidEye->SetGridConstraints(7, 1, 1, 1, CATGRID_4SIDES);
_EditorMidEye->SetReadOnly(TRUE);
_EditorMidEye->SetSensitivity(CATDlgDisable);

_LblRightEye = new CATDlgLabel(_FrmVolumetric, "LblRightEye");
_LblRightEye->SetGridConstraints(8, 0, 1, 1, CATGRID_4SIDES);
_EditorRightEye = new CATDlgEditor(_FrmVolumetric, "EditorRightEye");
_EditorRightEye->SetGridConstraints(8, 1, 1, 1, CATGRID_4SIDES);
_EditorRightEye->SetReadOnly(TRUE);
_EditorRightEye->SetSensitivity(CATDlgDisable);

_LblNeckPivot = new CATDlgLabel(_FrmVolumetric, "LblNeckPivot");
_LblNeckPivot->SetGridConstraints(9, 0, 1, 1, CATGRID_4SIDES);
_SpinnerNeckPivot = new CATDlgSpinner(_FrmVolumetric, "SpinnerNeckPivot", CATDlgSpnEntry|CATDlgSpnDouble);
_SpinnerNeckPivot->SetMinMaxStep(0.000000, 500.000000, 5.000000);
_SpinnerNeckPivot->SetValue(98.0);
_SpinnerNeckPivot->SetGridConstraints(9, 1, 1, 1, CATGRID_4SIDES);

_LblHeadRotation = new CATDlgLabel(_FrmVolumetric, "LblHeadRotation");
_LblHeadRotation->SetGridConstraints(10, 0, 1, 1, CATGRID_4SIDES);
_SpinnerHeadRotation = new CATDlgSpinner(_FrmVolumetric, "SpinnerHeadRotation", CATDlgSpnEntry|CATDlgSpnDouble);
_SpinnerHeadRotation->SetMinMaxStep(0.000000, 180.000000, 5.000000);
_SpinnerHeadRotation->SetValue(60.0);
_SpinnerHeadRotation->SetGridConstraints(10, 1, 1, 1, CATGRID_4SIDES);

_FrmDefinition->SetSensitivity(CATDlgDisable);
_FrmTargetSurface->SetSensitivity(CATDlgDisable);
_FrmSelSurface->SetSensitivity(CATDlgDisable);

_LablComputation->SetSensitivity(CATDlgDisable);
_Combo022->SetSensitivity(CATDlgDisable);
_ComboOrientation->SetSensitivity(CATDlgDisable);
_LblOrientation->SetSensitivity(CATDlgDisable);
_FrmSelSurface->SetSensitivity(CATDlgDisable);
_SpinnerOrientationDegree->SetSensitivity(CATDlgDisable);
_LblDiscretization->SetSensitivity(CATDlgDisable);
_LblAccurate->SetSensitivity(CATDlgDisable);
}

